### ISSUE TITLE
Proposal for a placeholder landing page design

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#10]
I'd like to propose this design as the very first version of the website for the Bitcoin Design community (decision on the domain is discussed [here](https://github.com/BitcoinDesign/Guide/issues/9)). I first submitted this for feedback last Friday in Slack [here](https://bitcoindesign.slack.com/archives/C018APVHLHW/p1595580469025800) and a variation of it on [July 8](https://bitcoindesign.slack.com/archives/C015856BDME/p1594199737397900). This page is built (on the Jekyll setup we [discussed](https://github.com/BitcoinDesign/Guide/issues/6)) and ready to go live if we want to (see it in action [here](https://gbks.github.io/bitcoin-design-guide/)).

<img width="2115" alt="Minimal site 2 200724" src="https://user-images.githubusercontent.com/695901/88523397-2eaab580-cff8-11ea-80d6-d294f82ac3b9.png">

The Figma file for the design is [published on the Figma community](https://www.figma.com/community/file/862622015964353400/Bitcoin-Designers-holding-page-idea), you are welcome to duplicate it, put your own spin on it and suggests improvements. If you want to comment on the design, check the [Figma source file here](https://www.figma.com/file/K5ahSqVzoMVBuhT5hAVRJr/Bitcoin-Designers-Website?node-id=31%3A231).

This is meant as a minimal, temporary placeholder so we can get something live soon. My sense from Slack conversations ([example](https://bitcoindesign.slack.com/archives/C018APVHLHW/p1595535231015200)) has been that many prefer to go live and iterate fast, compared to trying to build a more complete V1 that will take weeks/months to complete.

**Comment by BitcoinErrorLog** [comment]
I think it should be clear this is about UI and UX. "helping improve the design of **B**itcoin" sounds like we want to change how Bitcoin works or like there is something wrong with it. 

The sentence is also ill-formed, as I can't tell whether we are improving the design of the ecosystem, or whether we're implying we're improving the ecosystem with design or such.

Sorry for being nitpicky, but it is the only narrative on the page :)

Here's an alternate take:

"We are an open community of UX designers collaborating to make Bitcoin more user-friendly through thoughtful design."

**Comment by GBKS** [comment]
@BitcoinErrorLog thanks for the comment, this is exactly the stuff we need to discuss as a group.

**Comment by mayankchhabra** [comment]
Very neat and minimal! 

I think we should increase the font-weight of the Slack and GitHub links as their contrast with the white background is pretty low. I would have done that but couldn't get the fonts working in the Figma file, even though I've got the latest version of [Inter](https://github.com/rsms/inter) installed on my system. 

Also, is the white circle a placeholder for the Bitcoin Design logo/icon?

**Comment by AlexaAker** [comment]
I like the simplicity of the design you're suggesting. Thank you @GBKS & @pedromvpg. 🌟

I agree with @BitcoinErrorLog that the wording could be different. Perhaps we should include something like "for UI and UX improvement", rather than a community of "UX designers". This community could help bridge with developers and other community members that can be involved in the projects or in getting the resources they may need. 

@pedromvpg is it possible to have a dynamic element to the site, where some of the characteristics that describe the purpose of the community could be "swapped" after a certain amount of time, like certain words swapping in the white rectangle in the examples below?

The words could be what the community may suggest like people-friendliness, or like @BitcoinErrorLog points out, something related to UX or UI, for inclusion, for accessibility, and even something like "for all"... 

It may be clearer to label it Bitcoin Design Community or Bitcoin Design Open Source Community.

This example includes a possible heading and subheading for Bitcoin Design Open Source Community.

<img width="2115" alt="Minimal site 2 200724" src="https://user-images.githubusercontent.com/66574310/88596897-b362f700-d02b-11ea-9dd0-3bc3ec1b5e1c.png">

On Figma: https://www.figma.com/files/project/10979423/Bitcoin-Design-Community

An option on black with just Bitcoin Design Community.

<img width="2115" alt="Minimal site 2 200724" src="https://user-images.githubusercontent.com/66574310/88597161-42700f00-d02c-11ea-8021-2a32c93ce556.png">

**Comment by AlexaAker** [comment]
<h1>Space Inspiration</h1>
<h2>Possible Sections V2</h2>
<p>What about 3 main categories that start with the letter B, because of bitcoin.</p>
<h3>Begin.</h3> 
<p>A page or section on a scrolling page as @danielnordh suggests <a href="https://bitcoindesign.slack.com/archives/C015856BDME/p1595842837251500" title="Slack conversation" target="new">on slack</a>, which could focus on guiding people who may be new to bitcoin.</p>
<h3>Belong.</h3> 
<p>Perhaps both Join & Contribute should be merged into one section. It could include the links and explanation to contribute on Slack, Github, Figma…</p>
<h3>Beyond.</h3>
<p>This section could start housing resources for people or businesses wanting more specific guidance on topics related to bitcoin.</p>
<br> 
<p>And perhaps the About section could be Our Story.</p>
<p><i>What about space as an inspiration for some of the graphics in the site? As if reaching out to explore the bitcoin universe.</I></p>
<img width="2115" alt="Minimal site 2 200724" src="https://user-images.githubusercontent.com/66574310/89049760-5612c280-d317-11ea-9ddd-fe1351f7a773.png">
<p><a href="https://www.figma.com/file/1hQnXq8RUZC6BeS11VTBNk/Bitcoin-Design-Website-black-space?node-id=31%3A231" title="Space on Black" target="new">Space on Black &#10530; (On Figma)</a></p>
<br>
<img width="2115" alt="Minimal site 2 200724" src="https://user-images.githubusercontent.com/66574310/89050381-4c3d8f00-d318-11ea-9841-956b1c614d2d.png">
<p><a href="https://www.figma.com/file/hFd0flQf9o1lizRb2TL9JE/Bitcoin-Design-Website-white-space?node-id=31%3A231" title="Space on White" target="new">Space on White &#10530; (On Figma)</a></p>

**Comment by GBKS** [comment]
I also think that the headline needs to be carefully written. To simplify this, I created a Google Doc with the suggestions above and added some comments with the positives and negatives. Ideally we can brainstorm and discuss some more variations in that doc to find one we're happy with. [Take a look](https://docs.google.com/document/d/1BQ06jN-ev9b5DNgHmTmgSfq_c9wcV5-pOLKsY7fGRdM/edit?usp=sharing). For the concept with rotating words, I think the most important thing is to figure out what those words should be. Technically it's easy to implement.

For anything V2, I created a separate Github issue [right here](https://github.com/BitcoinDesign/Guide/issues/11).

For the black and white theme, we could simply use the approach of having a light and dark theme that switches based on time of day. It's a bit more work to design and implement, but might not be too bad if we start this from the beginning. I also messed around with this a little bit in the design below:
![Bitcoin guide site 200801](https://user-images.githubusercontent.com/695901/89102282-efb99d00-d407-11ea-85a5-25a38d7b4ef1.png)

**Comment by GBKS** [comment]
There was a bit of discussion around the headline in the Google Doc I linked to in my previous comments. I think we have something we can go with for now based on some iterations with input from a few different people and I implemented it in the linked pull request.

I'd love to wrap up this V1 and call it done so we can focus on V2 where we have at least a whole page with multiple sections to work out more details around how we talk about ourselves, how we guide people new to the community, etc. That will also give us more space to dive into visuals and concepts (like space, rotating words, etc).

Here's what it looks like:
<img width="2115" alt="Minimal site 200810" src="https://user-images.githubusercontent.com/695901/89798379-65bab400-db2c-11ea-946a-95cf7b21ddb1.png">

As before, the Figma file is public and can be duplicated by anyone to improve ([check it](https://www.figma.com/community/file/862622015964353400/Bitcoin-Designers-site)).

I know the capitalization thing is important to some people. I have no idea how to resolve these strong opinions, and probably not something that needs to be argued about in this thread. Maybe it can be be a separate issue if anyone wants to talk about it further.

Those are just my thoughts on trying to push site progress along. Let me know what your take is.

**Comment by Bosch-0** [comment]
Looks fine for a landing page, are we publishing this under bitcoin.design? Also is the white circle being filled with an icon or?

**Comment by GBKS** [comment]
@Bosch-0 domain is not finalized yet and there are some discussions around bitcoin.design in issue #9.

The white circle is intentional. I was trying to keep things as simple (or minimal) as possible and since it already says "Bitcoin" right below, I thought that would already be enough to communicate that this site is about Bitcoin. Bitcoin is already complicated enough, so my hunch is that this site should feel extremely simple overall (also something we should consider in illustrations, photos, creative concepts, etc).
