### ISSUE TITLE
Add tips for visual formatting of addresses to the `Glossary`> `Addresses` page

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Guide#107]
```meta
parent: Foundations
title: Addresses
permalink: /guide/foundations/addresses
```

See the glossary for description - this page should deal with the visual aspect of the address display.

- Address Versions (the different address types)
- Address compatibility
- Readability
- Visual Validation
- Display

**Comment by GBKS** [comment]
Do we still need this issue considering we now have a page about [addresses in the glossary](https://bitcoin.design/guide/glossary/address/)? That page doesn't deal with validation or display, so that's something we could add.

Looking forward towards Lightning, where users can enter a node ID for making keysend payments, we might need to expand on this topic also. There's a confusing amount of things you can input for a payment (Bitcoin URL scheme, Bitcoin address, Lightning node ID, Lightning invoice) that could be good to clarify.

**Comment by Bosch-0** [comment]
Agree with Christoph, these details could be shown in https://bitcoin.design/guide/glossary/address/. 

> where users can enter a node ID

I was thinking of adding Lightning node content to https://bitcoin.design/guide/glossary/node/, seems fitting. 

For invoices, what about a sub-glossary page that goes into all the invoice variations Johns has outlined here: https://bolt.fun/guide/invoices/variations.

Regarding keysends / node ID we should push for mapping node IDs to a contact list inside the users app and use this contact list for keysend payments, people shouldn't have to deal directly with node pubkeys.

**Comment by GBKS** [comment]
I'll rename this issue to match the previous comments (adding visual formatting info to the glossary address page vs adding a new page).

**Comment by GBKS** [comment]
Addressing this in #822.
