### ISSUE TITLE
Design a better social preview image

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#124]
Reported by @moneyball 

It seems we can add a social image that can pop a in people's timelines.

## What we currently have

![Screenshot from 2021-01-18 20-15-52](https://user-images.githubusercontent.com/36959754/104955136-fcd44380-59c9-11eb-89b8-2189edfe4a36.png)

## Template 
![repository-open-graph-template](https://user-images.githubusercontent.com/36959754/104955207-21c8b680-59ca-11eb-962c-84443b9f573a.png)

Someone can design it, then it'll need to be uploaded to the GitHub here.
![Screenshot from 2021-01-18 19-46-05](https://user-images.githubusercontent.com/36959754/104955060-d57d7680-59c9-11eb-83ed-ba6db75184b4.png)

**Comment by GBKS** [comment]
That particular link is for an issue in the meta repo. For repos, we can only add a single preview image that will be shown for all shared links to issues, PRs, etc. Otherwise it would be cool to use the cover images we already create for events as the previews. For the main site and all sub-pages, we have the ability to add page-specific preview images ("image" property at the top of each markdown file).

The outline image at the top is the default template I've used for a lot of pages. You can see them all in [Figma here](https://www.figma.com/file/K5ahSqVzoMVBuhT5hAVRJr/bitcoin.design?node-id=278%3A470). For pages that have a banner at the top, I've used resized versions of the banner visual for the preview, you can see [various examples here](https://www.figma.com/file/qzvCvqhSRx3Jq8aywaSjlr/Bitcoin-Design-Guide-Illustrations-CO?node-id=236%3A454). Also something that page authors need to prepare (and it's easily forgotten in the process).

I typical use a size of 1200x630 for these images. Different social networks use slightly different sizes, so they just never preview perfectly.

**Comment by GBKS** [comment]
Discussion happening in this [Slack thread](https://bitcoindesign.slack.com/archives/C0193ED2HT6/p1612799467010300).

**Comment by GBKS** [comment]
Trying to revive the Slack thread so we can get this done.

**Comment by sbddesign** [comment]
I've got two designs I'd like to submit for consideration. The stuff I have been throwing in to the Slack thread thus far is, in my view, too distracting to be used outside of the 4 quadrant context. So I am submitting two fresh options. One of them has a more modernist feel, the other has a video game style. I'm leaning towards the modernist version, but I wanted to throw the video game version up for consideration in case anyone feels it's good to have something more fun looking.

I'm also prepared to resize, reformat, recolor, or otherwise tweak these.

## modernist version
![bdc-social-preview_modernist-version](https://user-images.githubusercontent.com/2414177/110551343-507a2800-8103-11eb-9f61-cf240f837d3c.png)


## video game version
![bdc-social-preview_game-version](https://user-images.githubusercontent.com/2414177/110551354-54a64580-8103-11eb-996e-651cb955c92f.png)

**Comment by pavlenex** [comment]
@sbddesign Nice work, I like both of them. @GBKS Do we have some sort of official "branding" for the community by the way? Personally I think the second one may be more eye-popping in social media timelines. (The first one may look a bit unnoticeable in the darkmodes on Twitter, as it blends too much in, so if we'd like to go with more modern look, I'd go with Bitcoin orange and more vibrant colors.)

**Comment by GBKS** [comment]
The second one is definitely more eye-popping, due to the 3d. I don't like the grass and clouds and also find the colors more pleasant in the top one. I wonder if you can combine the two.

On a different note, I'm a huge sucker for these 3d icons with smooth lighting and shading ([example 1](https://dribbble.com/shots/12690247/attachments/4289434?mode=media), [example 2](https://pbs.twimg.com/media/Ejo7vcPXYAAVG4e?format=jpg&name=medium)). Do you know how easy or hard it is to do that in Blender? I might need to play with that sometime.

**Comment by sbddesign** [comment]
Here's some updated images incorporating feedback from @pavlenex and @GBKS 

It's a 3D coin, presented more in the style of the other design. Christoper, I attempted to mimic that look in the Dribbble links you provided. Blender is definitely capable of creating that look from a technical software perspective; it's all about getting the lighting and materials configured to perfection. Here's a first pass at that.

I favor the flat approach instead of tilted. The flat version looks dimensional in a very subtle way, I think. Thoughts?

## Tilted
![bitcoin-design-community_social-preview_3d-glossy_tilted](https://user-images.githubusercontent.com/2414177/110862508-864b1800-828d-11eb-86ec-8c34a91e83fe.png)

## Flat
![bitcoin-design-community_social-preview_3d-glossy](https://user-images.githubusercontent.com/2414177/110862526-8814db80-828d-11eb-820e-1606c1426ff3.png)

**Comment by GBKS** [comment]
Cool, I like the subtlety of the flat one also. Should we go with that one, or is there anything else to experiment with?

**Comment by pavlenex** [comment]
Nice, I like the flat one as well 🚀

**Comment by sbddesign** [comment]
I'm happy to tweak this further if anyone has ideas, but I went ahead and submitted PR #182 for this so we can keep thing moving.

**Comment by GBKS** [comment]
Resolved with PR #182 .
