### ISSUE TITLE
Clarify Projects page

### ISSUE THREAD

**Issue by danielnordh** [BitcoinDesign/Guide#162]
From the list of projects on this page https://bitcoin.design/projects/ it can be hard to know why they are on there (vs others), and what involvement the community has with each one.

We could clarify this, perhaps by splitting the the list up in sections:

- Community led projects / Led by...
- Collaborations

And perhaps we should consider dropping the ones that don't fit this bill.
For each of the above we could have a brief description of how they come about or where to find more info about the process.

**Comment by GBKS** [comment]
When I added the info about collaborations recently, I came up with three buckets of projects:

**1. Collaborations**
These are projects that we use our official collaboration process with. We want to showcase them, especially if we have case studies eventually, and have an open invite for projects. 

**2. Involvements**
Projects that somebody in the community is working with on their own initiative. These can turn into collaborations, or maybe designers want to team up with the current contributor.

**3. Interesting projects**
Projects we have no involvement with yet, but we think do fantastic work, and maybe we want to collaborate with them. This category has the most vague inclusion rules.

---

For all projects, it would be good to have the following info:
- Summary - what is this about?
- Design contribution resource links - what design problems do they have, how can I help?
- Design contacts - who can I talk to?
- Community links - let me snoop around a bit
- Website link
- Screenshots?

While the "Contribute" page is more general, this page can help people find specific projects, so I think it's a pretty important one to get right.

Those were my thoughts so far. What do you think?

**Comment by danielnordh** [comment]
_Interesting projects_ is a slippery slope to me. There might be better ways to provide exposure or express interest in working with them.

_Involvements_ I also find easily exposed to criticism. (Could this be someone helping out with a project, but getting paid, do we list projects that fit this criteria for all 900+ members, if not why)

**Comment by GBKS** [comment]
Is this similar to managing the Twitter account where we need some ground rules, and then rely on rough consensus?

**Comment by sbddesign** [comment]
Here is an idea I have about how to think of Projects. Divide projects into 2 groups. Perhaps these live on separate pages.

## Group 1 - Case Studies

The **purpose** of this group is to provide examples of how BDC can benefit projects.

These are projects which BDC has "officially" contributed to. An example would be something like where Specter, Zeus, etc presents their work to the BDC, then somebody from BDC goes and helps them with design. It could just include a little blurb about how BDC helped, and include a nice picture of what we did on the project.

Another example of projects that might fit into this category (in the future) is if a project credits the BDC with using Cristoph's UI toolkit, or otherwise credits the BDC with having helped their project.

## Group 2 - Index of BTC FOSS

The **purpose** of this group is to provide an index of FOSS projects for BTC.

Think of this as being a crowdsourced aggregated list of BTC FOSS. It's there so that people can discover other projects in the BTC space they may be interested in. Anyone who thinks a project should be added to this list can add it, either via pull-request or asking the BDC. The requirements for this list would be less strict than the case studies. Something like:

- Involves Bitcoin
- Is open-source
- Maybe some other criterion

**Comment by moneyball** [comment]
I agree something needs to be done here as the current page is misleading and not representative. If we cannot resolve some of the details raised in this issue, I'd still encourage us to make some decision sooner than later to clean up the existing page (like, before v1 launch), and unresolved issues can continue to be debated.

The website already explicitly links to "current collaborations" so that seems like a reasonable list to start with. https://github.com/BitcoinDesign/Meta/projects/2

**Comment by GBKS** [comment]
Alright, here's a revision that removes the "Projects we like" and splits the rest into community-initiated projects and project collaborations. How does that look?

For project collaborations, how specific do we want to be? Should we just explain what this project is about, or go into the nature of the collaboration? If you have a suggestion, a written example would be helpful. 

<img width="3180" alt="Projects page revision 210304" src="https://user-images.githubusercontent.com/695901/109987300-cbf46780-7d06-11eb-96c4-6c34b0011e43.png">

**Comment by sbddesign** [comment]
I like the way this looks. I think that going into the nature of the collaboration sounds nice, but could become complicated to describe due to the nature of open-source collaboration.

**Comment by moneyball** [comment]
@GBKS looks great. IMO let's merge and any further improvements can be done separately.

(one such potential further improvement would be to showcase all of the projects that have gone through design review, as I think it would be impressive to show the broader community the reach and impact the design review has.)

**Comment by pavlenex** [comment]
Concept ACK. Just a minor note, we've discussed that Wallet UI Kit may become the part of the Design Guide, since it gives concrete use-case to abstractions, I'm not sure how/if that's planned but putting it on a project's page makes it look like a separate project, which on the other hand gives better visibility to the Kit, was that the goal @GBKS ?

**Comment by GBKS** [comment]
@pavlenex TBH, I just added it so the Guide wasn't the only project in that list (it looked a bit lost). I see the guide and the UI kit as parallel projects. They have different goals, but are highly complementary and inform each other.

What else do you think will go in that list in the future? Should the icon set and hardware illustrations also be in there? Anything other than the guide and design resources we may end up having?

**Comment by GBKS** [comment]
Alright, I created PR #179 to address this. You can see the [preview here](https://deploy-preview-179--sad-borg-390916.netlify.app/projects/).

I removed all projects except for the guide, Zeus and Specter. Anything else that should go in this list? Does the header copy read well?

**Comment by GBKS** [comment]
Visualizing adding research and resource projects. Is this the direction we're working towards?

<img width="1063" alt="Projects page with extra projects 210310" src="https://user-images.githubusercontent.com/695901/110619117-b617f400-8197-11eb-94c9-124fee43f5c3.png">

**Comment by pavlenex** [comment]
ACK for displaying all of these community efforts, really good idea to include interviews and icons, these efforts indeed deserve visibility.
