### ISSUE TITLE
Develop coin control section

### ISSUE THREAD

**Issue by moneyball** [BitcoinDesign/Guide#22]
Already some great thinking here https://www.figma.com/file/mPoRMRTBOvi61M8psIp4XY/Coin-Control?node-id=0%3A1

**Comment by GBKS** [comment]
I'd love to see an outline of practical use cases for coin control.

It seems like actual coin selection is not an isolated UI thing, but part of general wallet management. Meaning that I only know which coins I want to select for a transaction when I have labelled my transactions/inputs properly beforehand (knowing where they came from), and understand why I should choose specific coins for a transaction to get whatever result I have in mind.

Not knowing a ton of detail, it would be ideal to avoid manual coin selection. What if the wallet can have a few coin control preferences that automatically picks coins for me? If it is connected to a full node, can it run some analysis and tell me what I should do?

As a user, I'd also like to know if I did my coin selection properly. How do I know whether it "worked"?

I personally would find it much easier to design an interface with these question discussed.

**Comment by GBKS** [comment]
We just talked about this in the [design review session](https://github.com/BitcoinDesign/Meta/issues/14). Two use cases that come up were:

1. Privacy, like not sending coins from well-known exchanges in specific transactions since that could expose some information about you
2. Bundling many small outputs into a single input to reduce fees for future transactions

With those in mind, it would be easier to create a more focused UI beyond general selection features. For example, a wallet can auto-detect if outputs are piling up and recommend a clean-up at an appropriate time. For the first case, a simple "Sender is an exchange" checkbox might suffice (or maybe a community-generated list of exchange addresses could be loaded in some privacy-preserving way) with a matching "Exclude exchange coins" during the send flow. Either way, a manual selection feature might be needed, with those smarter options layered on top.

**Comment by pedromvpg** [comment]
A while back I started playing around with this idea to test content creation on the guide in case that might be helpful:

- https://deploy-preview-20--sad-borg-390916.netlify.app/guide/wallet-components/output-selection
- https://www.figma.com/proto/iIK44j0nlUU9e5SUwNzBrO/Wallet-UX?node-id=77%3A1690&viewport=1686%2C444%2C0.15652310848236084&scaling=scale-down

Also some research done here 

- https://www.figma.com/file/iIK44j0nlUU9e5SUwNzBrO/Wallet-UX?node-id=77%3A2671

**Comment by Bosch-0** [comment]
Something to add that I mentioned in today's design review call around having buckets (though I prefer the term folders now). 
The idea is that users create 'folders' to group UTXOs based on various features (privacy being the primary one currently) similar to how someone would create a folder in their email client to organize their inbox (currently CoinControl UI is just an inbox - this is hard to navigate). 

This would exist alongside clever UTXO labeling (such as using hash based icons for each). A privacy focused example would be to only combine UTXOs within designated folders that have a set level of privacy associated with that folder. Instead of individually selecting UTXOs the user could just do something like 'send 0.253 BTC from folder x to address y' once they have assessed the threat model of the receiver. You could design the UI to look like an email inbox which would be familiar to most people with the folders on the left and UTXOs listed the right. 

Folder examples:

Taint free folder - Not concerned about privacy (e.g. UTXOs from close friends)
Minor taint folder - Moderately concerned about privacy (e.g. (UTXOs tied to sordid purchases) 
Tainted folder - Very concerned about privacy (e.g. UTXOs from a KYC exchange). 
Dust folder - contains small UTXO sets (user could even be prompted when this folder combined is worth consolidating and move combined UTXOs into another folder). 

Users should be able to create folders, name them what they want, give descriptions to folders and group UTXOs in them how they like.

If there is any major concerns with this idea let me know - keen to do up a mock up to illustrate this further.

**Comment by pedromvpg** [comment]
- Buckets
- Folders
- Groups 
- **Clusters** (like wasabi)

**Comment by moneyball** [comment]
@GBKS a drawback to simplifying and only presenting "is from an exchange" is that it doesn't capture other privacy-sensitive things such as
1) dust attacks
2) received coins can come from non-exchanges but still have PII associated with them (from a gaming site, from a merchant site like purse.io, from an employer, etc.)

**Comment by GBKS** [comment]
So much good information already in this thread, thanks everyone.

@pedromvpg good stuff. Is this something you are actively working on or more of an exploration to get thoughts "on paper"?

@Bosch-0 do you think this way of organizing transactions could be moved up to an account level? So just like I have a business and a personal account with my bank, I could have multiple accounts that match the taint risks you outlined but use a mental model that people are already familiar with (business, personal spending, social/friends/family, investment)? I am just thinking that all these organizational systems can so easily pile up, make the UI complex and confuse people. Maybe when you create an account, you can choose what privacy level you want to assign and then the UI gives you appropriate tips? Not sure what the right answer is, maybe a matter of mocking up ideas and prototyping...

@moneyball could dust attacks be automatically identified by wallets? Seems very suspicious to randomly receive a few satoshi.

And for PII, what are the risks? Tons of people these days use reward cards and seem comfortable when companies build profiles of their shopping behaviors. It would, of course, be great to prevent that, but in the end it's "fairly harmless" compared to risks like getting hacked and losing all your money.

Drilling down into all of these things might allow us to come up with some elegant solutions (I hope :)). I tried to summarize and structure things in this [Google Doc](https://docs.google.com/document/d/1KANRzXsjpt3JcAKea9WqIa8nCGwpHy5pfp-ImqnL3sQ/edit?usp=sharing), feel free to edit.

**Comment by Bosch-0** [comment]
Yeah you could have a structure like:

Account 1 - spending 
         -UTXO 'folder' one
         -UTXO 'folder' two
Account 2 - savings
          -UTXO 'folder' one
          -UTXO 'folder' two

etc. though this could get messy.

I'll think about this in more depth soon and do some mockups.

**Comment by moneyball** [comment]
Ledger just added support https://twitter.com/P3b7_/status/1305966436851089408

**Comment by GBKS** [comment]
These are the coin selection strategies Ledger supports ([source](https://github.com/LedgerHQ/ledger-live-desktop/blob/9a0043321d971118cc2e01134e258fe44ea410f3/static/i18n/de/app.json)).

<img width="425" alt="Screen Shot 2020-09-16 at 8 17 26 AM" src="https://user-images.githubusercontent.com/695901/93299259-10418900-f7f5-11ea-825c-571fb8c6642f.png">

**Comment by moneyball** [comment]
@GBKS yes good point about automatic detection of dust attacks. It isn't possible to be certain of one, but the pattern is pretty obvious as the minimum amount of sats is (537) is typically used in the attack. so if 537 sats is sent to an address that already has received bitcoin before could be flagged and perhaps a wallet would auto-freeze that UTXO and warn the user. This is a good example of a best practice we can share in our design guide and AFAIK no wallet does this.

**Comment by moneyball** [comment]
@GBKS regarding this: "And for PII, what are the risks? Tons of people these days use reward cards and seem comfortable when companies build profiles of their shopping behaviors. It would, of course, be great to prevent that, but in the end it's "fairly harmless" compared to risks like getting hacked and losing all your money."

Is this a question about financial privacy overall? I'd break it down into 2 things:
1) The blockchain is public. So to the extent that an individual's financial transactions are public that has more consequences than if only Visa, Square, or a government has access.
2) Society used to be cash-based which provided a level of privacy that today's digital money does not provide.

I'm not sure if I'm addressing your question so let me know if it is more nuanced.

**Comment by GBKS** [comment]
@moneyball bigger picture, what I am trying to figure out is how a user should practically think about these risks. This is something that also came up today in the Bitcoin Core GUI call and hebasto referred me to the [Privacy section of the Bitcoin wiki](https://en.bitcoin.it/Privacy). It has a really thorough outline, but also a great and case studies. I'll study this and see if helps me think through this better.

**Comment by s-5Q2X8mgeGR** [comment]
Sort of similar to the folder/groups/etc described above, I had following idea some time ago: https://bitcoindesign.slack.com/archives/C014BHV38EA/p1595323833349900, on what I've now started to think of as a "simplified coin control with presets", see attached PDF for example design using Blockstream Green. 

Concept: "Simplified coin control with presets"
- To get an receive addr, user select a suitable preset. Also, enter reference (label). 
- To send, select preset, and also enter reference.
- When sending, use preset-matching utxos as input to transactions. Eg., "From exchange" received UTXOs used in "To exchange" transaction. Additionally, when entering reference, offer autocomplete based on users prior entries, to also try match by reference. 

some things missing/could be interesting:
- while there's some existing presets (folders, groups, etc) that might fit most users, ability to add your own might be neat. 
- as noted on PDF, I think "selling" the why of label receive addrs (in my linked design example, select preset + enter reference) as first a "nicer overview" (From Bob +1 BTC, vs From bc1....9a2 +1 BTC), secondly privacy benefits, esp. for wallet apps that cater to people that have no idea bitcoin is using not an account modal. For this, a one-screen explainer when user first would go to 

Also shown in attached PDF is flow to manually select UTXOs. 

[Simplified coin control with presets (5).pdf](https://github.com/BitcoinDesign/Guide/files/5250684/Simplified.coin.control.with.presets.5.pdf)

**Comment by moneyball** [comment]
Concept ACK Simplified coin control with presets. Would love to see this as a good starting point for the design guide.

**Comment by GBKS** [comment]
@s-5Q2X8mgeGR your proposal is great. Would you be open to sharing your design source files for collaboration? Would be great to turn this into a clickable prototype, too.

When sending, I think it would be easier to be able to select a preset and the app picks the specific coins (instead of me having to pick coins).

Do you think the tags could be used in other areas of the app as well? From your proposed labels, there is some overlap with contacts. This might sound more complex initially, but might be easier once set up. So if I have you in my contacts and previously sent you bitcoin via the "Friends" preset, then it could automatically pick the right preset for the next transaction also and I just need to pick you from my contacts (which is more intuitive/personal, ignoring the potential address re-use issue for a moment).

Another use for presets (and contacts) is that the app can categorize my finances. It can show me how much I spend on "Goods and services" or how much I spent in fees for "Exchanges", etc.

It's always great when new features also make existing use/features better.

**Comment by s-5Q2X8mgeGR** [comment]
@GBKS 

**_Would you be open to sharing your design source files for collaboration? Would be great to turn this into a clickable prototype, too._**

For sure, will get done sometime this week, just gonna clean up figma file a bit first. 

**When sending, I think it would be easier to be able to select a preset and the app picks the specific coins (instead of me having to pick coins).**

Yes, this is what I propose in the design as well. The concept is to match the UTXOs based on same preset, and same reference if possible too. The "Select UTXOs" flows is just an extra flow for more advanced users. 

The overlap with contacts-- without solving the address re-use (which, without a centralized service involved, seems only possible with paynyms maybe), I don't see how this could make sense for the user. It'd be neat to, yes, select a recipient from contact book but it'd just add a lot of trust to various components. 

Yep, categorization of finances would be neat. Basically, for a mobile wallet appealing to new users, the closer we can get to an experience and functionality to a generic neobank mobile app, probably the better (without losing any of the core bitcoin properties, of course)

**Comment by GBKS** [comment]
@s-5Q2X8mgeGR sorry, totally missed that part about auto-select, thanks for the tip.

Regarding all this additional data wallets store locally, it would be ideal if there was some standardized formats so it could be easily ported and synced between wallets. Could include meta data for transactions and addresses (tags, descriptions), as well as a list of contacts. I bet somebody has already worked on something like this somewhere.

**Comment by s-5Q2X8mgeGR** [comment]
Attached is Figma file for the [above linked design](https://github.com/BitcoinDesign/Guide/files/5250684/Simplified.coin.control.with.presets.5.pdf) (not link, my Figma account's KYCd, need setup a bitcoin-only Figma account...) 

(zipped bc Github don't accept .fig) 
[Simplified coin control with presets.fig.zip](https://github.com/BitcoinDesign/Guide/files/5284927/Simplified.coin.control.with.presets.fig.zip)

**Comment by GBKS** [comment]
Thank you. Is it alright if I share a re-uploaded version of your Figma file that we can use to discuss and collaborate?

**Comment by s-5Q2X8mgeGR** [comment]
@GBKS yes, please do.

**Comment by GBKS** [comment]
And [here you go](https://www.figma.com/file/jdAqIWCVPRXudqiCYfXOUG/Simplified-coin-control-with-presets?node-id=0%3A1).

**Comment by statusquont** [comment]
I like the idea of tags better than folders. Having multiple tags give you more flexibility, whereas folders force you to choose one category. When sending you could filter all your UTXO's by multiple tags: show me all #spendable #KYC #CashApp for example. 

The wallet could ship with a few default tags (that get localized), and the user should be able to add their own as well.

**Comment by Bosch-0** [comment]
Could always use both tags and folders
