### ISSUE TITLE
Bitcoin icon only appears on mobile and tablet sized viewports

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#229]
The black bitcoin icon to the left of the Bitcoin Design text in the header is only shown on mobile and tablet sized view ports but not desktop - is this a feature or a bug? When scaling down the icon appears around ~995px width, any larger it disappears. shown below:

![Frame 6](https://user-images.githubusercontent.com/55287964/114516577-1e169a00-9c70-11eb-81fc-eaed6abf5495.png)

**Comment by GBKS** [comment]
That is intentional. @pavlenex mentioned a while back that the text was below the digital fold on mobile and users had to scroll before being able to get to the page title. Solution after some design exploration was to put the logo in the nav bar on mobile and keep it in the banner on desktop. See https://github.com/BitcoinDesign/Guide/pull/133

**Comment by Bosch-0** [comment]
Ahh okay no worries, sorry missed that :)
