### ISSUE TITLE
Add ability to view images in large overlay

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#267]
Currently images that have quite a lot of detail are hard to read on both mobile and desktop. An example being here https://bitcoin.design/guide/getting-started/common-user-flows/#sending-bitcoin. Being able to click on the image to view it in a larger overlay would be handy. Below is a very rough concept of what I mean: 

![Frame 42](https://user-images.githubusercontent.com/55287964/116343600-5513b080-a817-11eb-8462-f67f3168aee7.png)

**Comment by GBKS** [comment]
Do you see this as a generally useful thing, or just for this particular image?

In this scenario, we could probably also get by with just using the "full-width" layout option to allow for the images to stretch beyond the body content width.

Another approach, that works for this mock-up, is to link to the Figma file, as this is from the wallet UI kit. Might even be preferable as designers could go in directly and mess with the designs.

You can probably tell, I am looking to see if we can avoid it. Not always the case, but I think sometimes needing overlays is not needed when the images are well formatted and presented.

**Comment by Bosch-0** [comment]
Generally useful - there are quite a few images that would benefit with a alternate view. This is also good for accessibility to those who have bad vision. Increasing the width would still make it hard to read for this image in particular. 

Linking to the Figma file is a good option and should be included a alongside a larger view.

**Comment by pavlenex** [comment]
Concept ACK, I think this is a useful feature to have.

**Comment by GBKS** [comment]
This came up again in [yesterdays jam session](https://github.com/BitcoinDesign/Meta/issues/157). Overall idea is that the individual screens are interesting by themselves and readers may want to click to see them larger and get more detail (see the [Bitcoin UI Kit site](https://www.bitcoinuikit.com/screens/screen/cloud-backup-pin-entry) for an example.

Goals:
- Make screens easier to analyze (easier for designers to understand layout, copy, styling...)
- Provide extra info for each screen (easier for designers to understand design decisions)
- More closely link the guide and UI Kit (easier for designers to get to more useful resources)

Concerns:
- Introduces hidden content (text info that is not visible by default)
- We already have a caption below each image, what else do we want to write?
- Would this be a lot of overhead and complicate things to keep the guide and UI kit so closely in sync?

Alternative approach:
- For all static flows, include a clickable prototype and link to the Figma source (whether it's the  UI kit or not). See the [Savings account case study](https://bitcoin.design/guide/case-studies/savings-account/) for an example. Instead of just making images bigger and adding a bit more text, this provides more useful different perspectives of the UX

**Comment by pavlenex** [comment]
done in https://github.com/BitcoinDesign/Guide/pull/629
