### ISSUE TITLE
Use Figma live embeds for prototypes

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#275]
With Figma you can export an iframe of a prototype and embed it into the site so users can directly use it without leaving the Guide. Our current prototype setup is that users get send externally to Figma ([see example](https://bitcoin.design/guide/case-studies/multisig-wallet/#current--checking-account)). Here is a live video mockup of how this wold look / work, it would be pretty easy to implement just need to configure the media queries for iframes - I'll get to it soon unless someone else does this first :)

https://ttprivatenew.s3.amazonaws.com/pulse/raygrass_zeidae-aleeas/attachments/16712921/TinyTake30-04-2021-12-49-52.mp4

**Comment by GBKS** [comment]
Sorry, we can't use Figma embeds. We had this implemented some time back with the case studies, but removed it due to performance and privacy issues. Each embed required multiple MB of download, including 400KB of tracking scripts that sent  your data to Twitter, Google, Facebook, and LinkedIn. I had sent these concerns to Figma but got no response.

**Comment by Bosch-0** [comment]
Makes sense, will close!

**Comment by GBKS** [comment]
Looked into this again, and looks like they improved their tracking. Only tracking going out now is to segment.io (which doesn't change much as it's a service that aggregates data from various sources). We still have a few issues with Figma embeds:
- Loading a prototype of a mobile app on desktop shows a phone frame around the screen. On mobile, it doesn't. Tricky inconsistency, which can lead to not being able to tell that you're looking at a prototype because it blends with the background
- On mobile, the iframe captures your touch and swipe interactions. So it gets hard to scroll past it to content further down.
- Still 2.9 MB of download for a simple prototype (700KB of that is fonts), and tracking (although less intrusive).

This stuff may sound minor, but it feels really off when you implement it and play with it. So my vote is still for our current approach of static images that link out to prototypes.
