### ISSUE TITLE
Explore solutions for letting users choose transaction fees.

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#4]
Fees can get expensive at times and have a big influence on how long transactions take to confirm. There are various details to consider when designing a fee picker, let's come up with some good recommendations.

[Slack thread](https://bitcoindesign.slack.com/archives/C014J9ZKXB4/p1594309912465100)
[Figma](https://www.figma.com/file/egyOrvQJr0LK20fdOKXoBQ/Bitcoin-transaction-fees?node-id=0%3A1)

**Comment by BitcoinErrorLog** [comment]
I like having Custom as an option, and I like the idea of a weather report message like "Fees are lower than usual" as shown. The chart feels possibly unnecessary, maybe a text interpretation would be better, something like "Fees are currently 10% lower than the monthly average." Getting in the weeds though...

I think a slider is too much mental friction, due to thinking about what price i wanna pay exactly and then achieving precision.

**Comment by Bosch-0** [comment]
I agree with not having a slider. 

I like having the 3 fee options, slow, medium, fast with the ability to open more advanced fee settings such as complete custom fee / view of chart etc. 

+1 error logs suggestion with having a tool tip say if the fees are lower than usual. To take it a step further It would be handy if my wallet could give me a notification if the mempool is clearing 1 sat/byte txs (or any low amount) so I can hop in and consolidate UTXOs / send transactions i've been holding off on. I always forget to check when rates are low as im sure many others do!

**Comment by GBKS** [comment]
In honor of the issue turning 1 year old, I'd like to send it off to retirement. We have info about fee picking [in the guide](https://bitcoin.design/guide/payments/send/#setting-the-transaction-fee) (and the UI kit). If there's more to be done, a new issue can be opened.
