### ISSUE TITLE
Custom styling and interaction model for the glossary

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#43]
The glossary page will get pretty long and tedious to use. Here's a suggested design where all terms are collapsed by default and can be expanded. There's also an inline search-bar to instantly filter the page content as the user types, to more quickly get to what they are looking for.

![glossary-201021](https://user-images.githubusercontent.com/695901/96706243-9faefe80-1396-11eb-9b19-43a4f09bfea5.jpg)

Here's the [design in Figma](https://www.figma.com/file/K5ahSqVzoMVBuhT5hAVRJr/Bitcoin-Designers-Website?node-id=304%3A577).

**Comment by ImTiaan** [comment]
Grabbing this one =)

**Comment by GBKS** [comment]
@ImTiaan are you still planning to work on these improvements for the glossary page?

**Comment by ImTiaan** [comment]
> @ImTiaan are you still planning to work on these improvements for the glossary page?

@GBKS yup, mentioned to @ConorOkus I was tackling it this upcoming weekend - been on a hellish few sprints to get some stuff ready for a work launch

**Comment by danielnordh** [comment]
With this change (that seems good) I'd just want to make sure that if I link to a term from elsewhere in the guide there's a way to land on the expanded version?

**Comment by GBKS** [comment]
Yep, that's possible. We just need to check the URL on page load for a "#" fragment, then see if it matches an ID on the page, and expand that section.

We can also update the URL accordingly as you expand/collapse definitions, to make it easier to find the right deep-link.

**Comment by pavlenex** [comment]
I am fan of the concept. I'd like to suggest one more thing though, we should have an easy way for people to copy specific portions of the glossary's titles. For example `/glossary/#address` just a link styling so that people can easily copy/paste and link to section of the guide. 

I think with information we already have and will have in the future, people will definitely want an easy way to reference to certain parts in articles, researches, forums, etc.

Technically speaking I suggest we add `a.header-anchor`
 Example https://css-tricks.com/link-header-header-link/#clickable-area
