### ISSUE TITLE
Add information about 21 million cap to the "Why Bitcoin is unique" page

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Guide#433]
**Describe your content request**

Hello, I would like to request an update to the "Why Bitcoin is unique" page.

**Link to the page**
https://bitcoin.design/guide/getting-started/why-bitcoin-is-unique/

**Why would you like to change the content?**
- Include information about limited supply of bitcoin and why it makes bitcoin unique

**Suggestions**
- N/A

**Content guidelines**
If you're a contributor looking to tackle the issue, you can [preview our content guidelines](https://bitcoin.design/guide/contribute/content-guidelines/).

**Comment by Bosch-0** [comment]
Relevant to this thread https://bips.xyz/42

**Comment by GBKS** [comment]
[Here's a graphic](https://www.figma.com/file/qzvCvqhSRx3Jq8aywaSjlr/Bitcoin-Design-Guide-Illustrations-CO?node-id=198%3A2914) to visualize the supply curve. I had put this together for the "Tech primer" page initially, and cut it at the time because it didn't flow well with the page and the economic dynamics of Bitcoin seemed like a whole separate topic, potentially worth having a dedicated page. That image is already on Github ("assets/images/guide/getting-started/technology/supply@2x.jpg") in case you want to use it here.

![supply@2x](https://user-images.githubusercontent.com/695901/128690328-c74d1246-feb5-4e25-a8cc-29ad0e8989ea.jpg)

**Comment by GBKS** [comment]
Tackling this one via #477.
