### ISSUE TITLE
Improve the image on the Setting the transaction fee section 

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#435]
**Request the visual**

Hello, I would like to request an improvement of the existing visual for the Setting the Transaction Fee paragraph in the Payments > Sending Bitcoin section.

The feedback from Slack 

> Also, what is the “G” supposed to mean within the “Transaction fee” section?

points out that the G for Haitian Goud isn't quite clear, so we should try to use something a bit more standard (which also means we should probably update the `Inputting an amount` section?

> Also, what is the “G” supposed to mean within the “Transaction fee” section?

**Link to the page**

https://bitcoin.design/guide/payments/send/#setting-the-transaction-fee

**Visual Type**

- Modification of the existing content image 

![Screenshot 2021-07-28 at 22 20 29](https://user-images.githubusercontent.com/36959754/127390628-14ff86a1-10ce-4741-8d7e-3bdf61a3b229.png)

**Additional context**

![Screenshot 2021-07-28 at 22 23 06](https://user-images.githubusercontent.com/36959754/127390657-73a97360-5fc4-43cf-9e47-d288d31a936d.png)

** Alternative Solution**

Alternatively we can explain the currency in the image caption.

**Illustration guidelines**
If you're a contributor looking to tackle the issue, you can [preview our illustration guidelines](https://bitcoin.design/guide/contribute/illustration-guidelines/).

**Comment by pavlenex** [comment]
Additional feedback posted on Slack emphasises that /vB

> Also, what is the “G” supposed to mean within the “Transaction fee” section?

> Virtual Byte (it’s the size of the transaction)

> When you pay the transaction it is calculated by fee rate * vB

> The higher the fee rate the higher priority miners would give.

**Comment by Bosch-0** [comment]
A link to the Figma source for this file would be handy. 

> points out that the G for Haitian Goud isn't quite clear, so we should try to use something a bit more standard (which also means we should probably update the Inputting an amount section?

We should stick with using one fiat denomination guide wide, I'd recommend USD as it is most universally known. At first glance the 'G' confused me. 

> Additional feedback posted on Slack emphasises that /vB reference in the image may not be clear either (we can link to it, explain it in the caption?)

Explaining what vB is here would be a good addition, could slide it in with the updated image PR.

**Comment by GBKS** [comment]
@johnsBeharry specifically picked out the Haitian Gourde, those particular names, and the scenario of paying an overseas designer to include a global use case (that Johns has personally experienced) and some diversity into the content. I think that's great. I'd opt for clarifying this scenario and embrace this idea instead of always going for USD. I think it can work very well with a few tweaks.

As for vB and the calculation, I think we should either remove it and just show the final fee itself, or hide it in a way that users can access it if they want to see the breakdown. IMHO, it makes no sense to show vBs to regular users. When I talked to Johns about it a while back, we were discussing this as well.

**Comment by pavlenex** [comment]
We can always add a caption in the image to explain that  `G` stands for `Haitian Gourde` ?

> As for vB and the calculation, I think we should either remove it and just show the final fee itself, or hide it in a way that users can access it if they want to see the breakdown. IMHO, it makes no sense to show vBs to regular users. When I talked to Johns about it a while back, we were discussing this as well.

Coccept ACK.

**Comment by Bosch-0** [comment]
Here is a mockup based on discussions above / some other suggestions I had for this image. 

![image](https://user-images.githubusercontent.com/55287964/128455061-a91b7f96-9557-4264-bdb8-75d9e28b6d2c.png)

- Two options to choose from is a better UX imo, not sure of many cases were a 'Medium' option would be picked. I think if there is to be three options it should be Instant, urgent, non-urgent. Instant defaulting to Lightning payment (though this is a discussion for another time).
- The title of the image is 'How urgent is this payment?' so naming the options 'Non-urgent' and 'Urgent' is more clear imo than low, medium, high.
- The boxes should show the sat amount, not the vB, as this is what information is most clear / relevant to the user and vB is shown below so there is no need to display this information here as well. 
- Maybe a personal preference but I like to show the fiat denomination after the amount as that is generally how you read that information (moved G from left to right side if that wasn't clear).
- Made the selected option outline slightly thicker and gave it a low opacity orange fill just to make it pop a little more. 
- For the urgent option (previously high) I think 10-20 mins (1-2 blocks) is more accurate than 8-10 mins. 
- Removed time until confirmation from the secondary details menu, this is already communicated in the boxes above when picking your urgency. 
- Also in the secondary menu I emphasized the data instead of the data label as that is what is the higher priority information. 
- Displayed the total fees in sats rather than BTC. I think we we are beginning to assume LN guide wide using sats > BTC where relevant is a good step to take. Using sats also makes it more clear as to what the sat/vB labels mean and how that total fee was calculated. 
- Added a caption explaining what vB and G mean as mentioned above.

**Comment by GBKS** [comment]
Really appreciate the detailed discussion on this. Your comment on reducing options made me think about removing the "Standard / Custom" toggle and fee rate into, see the mockup below. The custom option is now de-emphasized and secondary to the defaults, and fee rates can be pulled up for a detailed breakdown.

One of my theories around 3 options is that the middle one should always be the one that works best in most scenarios, a really great default people can rely on. Then the other options become more obvious as "I am in a hurry" and "I don't care how long it takes". With 2 options, I am forced to pick. Not sure if people really think that way, but I personally find it intuitive. 2 options could also work.

Good idea with the caption, this could be an actual HTML caption in the page instead of being baked into the image.

If you want to switch to sats, make sure to also update the other images on the page so it's all consistent. Didn't check if your other tweaks would also need to be carried over to other visuals.

![select-fee-rate](https://user-images.githubusercontent.com/695901/128460007-82917163-ea22-4b82-97b9-f637da38e11c.png)

**Comment by Bosch-0** [comment]
> Your comment on reducing options made me think about removing the "Standard / Custom"

This is the way I went with Zeus also, very similar to what you've done above.

![image](https://user-images.githubusercontent.com/55287964/128462727-3722b2c4-dd1f-4afc-9bca-80da735d4d1a.png)

> One of my theories around 3 options is that the middle one should always be the one that works best in most scenarios, a really great default people can rely on.

I like having Fast, Slow and custom for everything in between, if you add a medium that's 4 things to choose from. 

Bit of a side note but something I don't see many wallets doing is allowing the user to set a time rather than a price in the custom option. So say I could say Custom -> Confirm in 45 minutes and it would estimate that cost. Entering vB is always more burdensome as you have to: 1. Look up current fees are 2. Understand what vB means 3. Tweak the vB amount to get a desired time. Say if you pay rent when you get paid on a Tuesday but it isn't due until Friday you could say 'Confirm in 3 days' so it only confirms when it is necessary to confirm giving you an optimal balance of fees / speed. If for example you wanted to achieve this but you entered vB instead the UX would be much worse as 1. The fees may change in that time meaning you over/underpay 2. You'd have to sit there and find an optimal vB that equaled 3 days so the payment was confirmed on the day it was due. 

> Good idea with the caption, this could be an actual HTML caption in the page instead of being baked into the image.

Yep this would be better. 

> If you want to switch to sats, make sure to also update the other images on the page so it's all consistent. Didn't check if your other tweaks would also need to be carried over to other visuals.

We should open an tracking issue and make sats guide wide. But yeah I'll make changes to the other images also if relevant.

**Comment by GBKS** [comment]
I like what you did with Zeus there. Personally, I would probably never use the Custom option and deemphasize it.

I wonder how often the transaction size is important. Maybe it's enough to hide it unless there's a fringe case? For example, "This transaction is more expensive than usual due to its size. Learn more", with an explainer about how it includes a lot of change inputs or whatever the reason may be.

Not sure we have consensus on using Sats across everything. I am planning to work on the Units & Symbols page the next 1-2 weeks, maybe the conversations around that will help shape a direction?

**Comment by Bosch-0** [comment]
> I like what you did with Zeus there. Personally, I would probably never use the Custom option and deemphasize it.

For extreme UX focused wallets completely agree, Zeus is for those more turbo users who will likely use this feature a bit.  Could just have a (...) menu up the top right that users can click and set a custom fee from. 

> I wonder how often the transaction size is important. Maybe it's enough to hide it unless there's a fringe case? For example, "This transaction is more expensive than usual due to its size. Learn more", with an explainer about how it includes a lot of change inputs or whatever the reason may be.

Can probably be omitted and included in some transactions setting menu. Yeah a small warning dialog could pop up if its larger than normal (lots of UTXOs being used, non-segwit etc). 

> Not sure we have consensus on using Sats across everything. I am planning to work on the Units & Symbols page the next 1-2 weeks, maybe the conversations around that will help shape a direction?

Sounds good to me !

**Comment by GBKS** [comment]
@Bosch-0 are you planning to create a PR for this?

**Comment by Bosch-0** [comment]
PR for this issue https://github.com/BitcoinDesign/Guide/pull/458
