### ISSUE TITLE
The proposed Units & Symbols in the bitcoin.design guide are hardly readable.

### ISSUE THREAD

**Issue by viaj3ro** [BitcoinDesign/Guide#455]
Today I stumbled across this tweet from Christoph Ono:
https://twitter.com/GBKS/status/1427169492971540480

Where he proposes the following Units & Symbols for the design guide:

![image](https://user-images.githubusercontent.com/42124006/129600201-484939fb-304c-4b7c-aeae-b798531dc9ce.png)

I think this is extremely hard to read and something like this would be much better:

10,110.10'199'290;123

This way BTC amount AND Satoshi amount and even millisats become instantly readable!

**Comment by GBKS** [comment]
Thanks for chiming in on this. The image is more meant as an introduction to the topic identifying the different aspects of formatting to consider, not a specific proposal. I totally didn't realize people would see it as a proposal when I posted it, but I can see why. The full page about units & symbols is in the PR #63. You can preview the page [here](https://deploy-preview-63--sad-borg-390916.netlify.app/guide/payments/units-and-symbols/). Feedback is highly welcome.

After working on the page and researching this, I am not sure it is our place (as a Bitcoin community) to propose a single solution. There are a lot of different standards (for math and currency) across countries and languages, with users having learned certain formatting their whole lives. I think there are some places where we can provide guidance, like the 8 digits, but otherwise my recommendation is to follow i18n practices like we do with dates, temperature, distances, etc.

How did you come up with your proposal? I'm curious to hear the train of thought.

**Comment by viaj3ro** [comment]
> How did you come up with your proposal? I'm curious to hear the train of thought.

I run the LN node SilentBob and therefor have to deal with full bitcoins, sats and even millisats on a daily basis. If you just use sats, everything becomes quite easy and straight forward. It's basically the same as dealing with Indonesian Rupiah since 1 sat ~ 8 rp. Unfortunately most people don't yet realize that it's actually quite easy to get accustomed to dealing with large numbers and all our unit problems would be gone instantly. Even the unit bias... Until people realize that (I'm pretty sure it's only a matter of time and the lightning network will hopefully accelerate it), we still have to deal with full BTC as denominator.

My proposal seeks to be a good solution to get both (the BTC and the sats denominated world) together and make it intuitive to read BTC, sats and millisats right away and without counting numbers (which is a serious pain in the ass!)

**Comment by Bosch-0** [comment]
> 10,110.10'199'290;123

To me, this isn't clear, I'm not sure what I'm reading tbh. Is this a convention used elsewhere in the world? I'm in Australia and have never came across integers being separated with '. 

I can attest to people dealing with large numbers when visiting Indonesia though as it's somewhere I've been many times and experienced this first hand. Everything being denominated in sats is the way forward imo, especially as the price increases. 

I've been warming up to this representation of showing both BTC / sats amounts, what do you think of this @viaj3ro? It's got much less visual elements that are likely to be confusing to some demographics (as I am with the above proposed solution). 

![image](https://user-images.githubusercontent.com/55287964/129654902-d7ca275e-3640-4fe8-88ff-2eec8b4645b9.png)

**Comment by pavlenex** [comment]
Spaces fix everything imo 

`100 000 000 SATS`

**Comment by GBKS** [comment]
Thanks for the extra detail. I think it shows that there is no single universal solution, but that we need contextually appropriate formatting.

Here's how I'd go about this logically:
1. I'd separate the discussion around separators (commas, dots, mid-dots, apostrophes...) as that is a matter of local standards of mathematic annotation (not even a currency issue).
2. If we exclude that, then what we're left with is the question of defaulting to bitcoin or sats (I don't see bits as a serious contender long-term) and in each case how we format very large and very small numbers (for which there are also standards). 
3. Bitcoin vs. sats is probably a matter of use case (investing, Lightning micro-payments, etc) as well as personal preference. 
4. Since applications can't know the personal preference, they should pick smart defaults based on use case, and then allow users to adjust the setting.

That's my general approach.

**Comment by viaj3ro** [comment]
Honestly, I truly don't care what symbol is used as a seperator. What matters is, that sats are readable. Meaning no omitted zeros at the end and the seperator should be 1.00 000 000 and not 1.000 00 000 like previously suggested.

**Comment by GBKS** [comment]
Which applications do your primarily use? We can take a look and propose design suggestions to them.

**Comment by viaj3ro** [comment]
The apps I'm using all offer denomination in sats, which works well for me.

I do use blockstream.info on a regular basis though and they don't even show tx fees paid in sats. On top of it, they omit trailing zeros which makes reading the tx fee a pain in the ass. They don't use github for the explorer unfortunately, otherwise I'd have already reported the issue. I tried via public channels, but no luck.

Feel free to get in touch with them, if you're able to get through. They should show tx fees in sats, at the very least!

**Comment by pavlenex** [comment]
Since this `issue` is part of the `PR` that has not been added to the guide yet, I'll close it in favor of #63 and invite people interested to comment on a PR directly and help us review it.
