### ISSUE TITLE
Recommend warning users if fee estimation or selected fee is too high

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Guide#456]
**Describe your content request**

Hello, I would like to request an update to the [sending bitcoin page](https://bitcoin.design/guide/payments/send/) page so it recommends warning users that the transaction fee is too high.

![5jsb2d](https://user-images.githubusercontent.com/183140/129609527-9116f34b-3656-4bf1-a61e-a389a484602a.jpg)

**Link to the page**
- https://bitcoin.design/guide/payments/send/

**Why would you like to change the content?**
In the events that the fee estimator is not providing accurate results, or if the user chooses to input their own custom fee, the application should inform them that the fees are too damn high.

An example of user error could be mistaking the custom fee estimation for the amount being sent. Seen a story about this somewhere on the internets. Another more likely possibility is the fee estimation not being optimised, or in fact broken/offline which can be a dangerous situation if the user depends on these automatic calculations and does not understand what "normal" fees are.

**Suggestions**
On the "[Setting the transaction fee](https://bitcoin.design/guide/payments/send/#setting-the-transaction-fee)" section:

- Add do/don'ts warn the user that they may be overpaying if the estimated fee, or custom fee is higher than some amount (lets discuss this).

On the "[Reviewing and approving the payment](https://bitcoin.design/guide/payments/send/#reviewing-and-approving-the-payment)" section:

- Add do/don't for showing a warning about fee's being too high before transaction is broadcasted
- Update/Add image to show the same warning

**Additional context**

Suggestion from @patestevao, takeaway from her [BitcoinUX research](https://github.com/patestevao/BitcoinUX-report/blob/master/report.md).

**Content guidelines**
If you're a contributor looking to tackle the issue, you can [preview our content guidelines](https://bitcoin.design/guide/contribute/content-guidelines/).

**Comment by pavlenex** [comment]
Requested in #454, but will close that one since you explained it better.

**Comment by Bosch-0** [comment]
The biggest UX issue I see with people regarding on-chain fees (and the one pointed out in Patricia's research) is people paying relatively large amounts for small purchases, I don't often see people doing large payments complaining about overpaying fees, I'd assume this is due to relatively wise the fee is still small, this is still not the best scenario but not the most important UX aspect of fees to address imo but I've attempted to address both below. 

Having a % threshold would be a good way to mitigate the issue with large relative fee for small payments. Say if the fees go over 2% (represented in sats) of the payment a tool tip is shown warning the user they are overpaying. 

Maybe if this threshold is met and it's cheaper to use LN (if channels present or not) it automatically opts for a LN payment - though we'll keep this for another discussion. 

Another option would be to do some math behind the scenes to calculate if the fees are relatively high based on say the previous 2016 blocks (2 weeks). If a fee spike has occurred in that time (say a 50% increase during that period) the app should give a warning that fees have recently spiked and maybe waiting for them to go down before sending is a better option.

You could realistically deploy both of these methods together, the first directly addresses the UX issue of paying large relative amounts compared to the payment amount and the second covers all other scenarios for overpaying.

**Comment by Bosch-0** [comment]
From @patestevao's research 

> Fees fluctuation
> 
> One of the most common issues shared by participants, no matter how much technical knowledge they had, was regarding fees instability.
> 
> How come it is so frequent to hear stories of people accidentally making payments with a value lower than the fees they paid? One can argue that the main chain should not be used for low-value payments, which indeed can be a valid view. However, it does not provide a solution to the problem, it just says that you should avoid having this problem.
> 
> What is fascinating about this issue is that it reveals how even technically savvy users will need a good UX in the end. It doesn't matter how much of a computer genius you are, you are likely in a relaxed or casual mindset when you are buying a cup of coffee. One way to put it is that everyone can play the role of multiple personas in real life depending on the moment they are.
> 
> Possible approaches to deal with this particular user problem can be:
> 
> * Warn users if the fee market is in a surge. The warning can be textual or visual.
> * Warn users if they are sending a payment too low relative to the fee they are paying. This can be a percentage defined by the wallet creators. For example, show a warning if the fee is 80% the value of the payment.
>  * Maybe even suggest that they perform the transactions later if they are not in a rush.
>  * Create programmable transactions based on fees, similar to orders you can place on an exchange. The user would choose something like "I want to send this transaction when the suggested market fee is lower than 5 dollars".
>  * Allow users to set a warning threshold, such as "warn me every time the automatic fee is above 10 dollars."

**Comment by johnsBeharry** [comment]
re Patricia's research: tx batching can also be an approach to lower the payments' cost.

**Comment by paulosacramento** [comment]
> re Patricia's research: tx batching can also be an approach to lower the payments' cost.

Hi @johnsBeharry . Can transaction batching be used by a single user of a non-custodial wallet? I don't see how this could be possible... Or maybe I didn't understand what you mean...

**Comment by Bosch-0** [comment]
> Can transaction batching be used by a single user of a non-custodial wallet?

Yes this is possible, bluewallet is a user friendly wallet that lets you simply send to multiple addresses (batching) in the one transaction. It's easier to grasp when you think of a transaction as like a 'mini-ledger' that you append to the blockchain rather than it being something that's an A->B process you'd think of in conventional payment systems.

**Comment by GBKS** [comment]
Addressing this in #825 with some if already covered in #817.
