### ISSUE TITLE
Add ⚡️ content to `Getting Started` > `Visual Language`

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#464]
**Describe your content request**

It's been discussed on a Jam Session that we open up the issues for the pages in the `Getting Started` section that should be revised and require Lightning Network content.

**Link to the page**

https://bitcoin.design/guide/getting-started/visual-language/

_Please add a link to the page you're requesting content change for (if applicable)_

** Discussing what needs to be added to the page** 

Please, review the current state of the page and feel free to discuss what kind of LN content should be added (if any).

**Content guidelines**
If you're a contributor looking to tackle the issue, you can [preview our content guidelines](https://bitcoin.design/guide/contribute/content-guidelines/).

**Comment by pavlenex** [comment]
@sbddesign and @danielnordh mention this page should mention:
- Mention Lightning Bolt symbol ⚡️ 
- Add a link to the Units & Symbol page #63

**Comment by sbddesign** [comment]
@pavlenex I'll step up and lead this page, if you would like to assign me.

**Comment by pavlenex** [comment]
Related #205

**Comment by sbddesign** [comment]
Here is a first draft of this content.
[Visual Language - Lightning Content](https://docs.google.com/document/d/1O5IjJHYq-NPbUllIXqo-wQtcjZve3VUtDOCfEmyTqgQ/edit?usp=sharing)

If you dig into the version history of the document, you will see where I started by bringing in the existing Guide content. The most recent version includes my LN additions. I thought it would be useful to briefly talk about the sats symbol (since we spend a good bit of space talking about the Bitcoin symbol) and then spend some time talking about lightning related imagery.

@GBKS I was reading #205 just now and it sounded like you had started doing some work around adding the sats symbol to the page. If there is anything you have already produced here, let me know.

**Comment by GBKS** [comment]
Yes, I've been meaning to add info about the Sats symbol forever. My thinking is that it just needs a small section stating that some people think that there needs to be a dedicated currency symbol for Satoshis, but that there is no established consensus (whether a symbol is needed, and if so, what it should look like). This could be accompanied by a grid of symbol proposals via the linked Figma file in #205. Would be great to add during this revision, but I can also tackle it separately.
