### ISSUE TITLE
Add ⚡️ content to `Designing Bitcoin Products` > `Open design`

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#484]
Add Lightning-related content to the [Open design](https://bitcoin.design/guide/designing-products/open-design/) page, as appropriate. This page likely needs only minor tweaks, if any. See [notes](https://docs.google.com/document/d/1JwNSJj_2_IxUcx81cbl7sa6XdPZEGduRiprTm3Y2E4o/edit?usp=sharing) from [Jam Session #14](https://github.com/BitcoinDesign/Meta/issues/120).

Secondary, do a general review of this page (check overlap with other pages, add relevant cross-links...) and check open issues for changes on this page and implement them.

Alexa wanted to see if there's an opportunity to add information about accessibility to this page.

**Comment by AlexaAker** [comment]
Looking through this page ended up being a good exercise on Open Design. Thank you @GBKS. 

Tried to figure out the essence of each paragraph, simplify it a bit, combine a few paragraphs and sections. Looking at it directly through Figma in order to rearrange and rethink content. 

https://www.figma.com/file/96czLwWoofS32a2DG9obQB/open-design?node-id=0%3A1

![1-thought-process](https://user-images.githubusercontent.com/66574310/136825137-305cc148-a83b-4aed-86e2-92d713e45c8c.png)

![2-work-in-progress](https://user-images.githubusercontent.com/66574310/136825156-f2166725-e24d-443a-b2f7-4d06eed2bec3.png)

**Comment by GBKS** [comment]
Just reviewed your Figma. This is great, Alexa. Is the next step to create a PR to review the copy in the site framework?

**Comment by AlexaAker** [comment]
> Let me know if you need any support with creating the PR @AlexaAker!? Would be great to wrap this up.

Thank you, Daniel.
