### ISSUE TITLE
Orphan Control

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#527]
I suggest we try to implement some form of orphan control. Is this a critical high-priority issue? No. But we're designers here and seeing stuff like this (circled in red) in the Guide drives me crazy. 😂

My go-to hack is `&nbsp;` but @GBKS suggests [text-balancer](https://github.com/nytimes/text-balancer).

<img width="870" alt="Screen Shot 2021-10-15 at 11 27 26 AM" src="https://user-images.githubusercontent.com/2414177/137513264-545f1102-5ec3-406b-85a1-e4204f81fd18.png">

**Comment by GBKS** [comment]
The big thing with orphans is that you never know when they appear due to our infinite variations in screen sizes (and user-control over font sizes due to accessibility, etc). That's why I prefer an automated solution. Otherwise you really need to add a non-breaking space between the last two words of every single title and paragraph (if you want to be 100% covered).

**Comment by GBKS** [comment]
Is this something to consider still?

**Comment by sbddesign** [comment]
Yeah, it just hasn't been at the top of the priority list. I can take a look at it.

**Comment by GBKS** [comment]
Addressing runts (I was taught they were called orphans in design school, but apparently runt is the right term) on image captions in #751. Very simply solution. To apply this for all content, we'd need something more sophisticated.

**Comment by GBKS** [comment]
#751 was merged, so I consider this issue done as it only pointed out image captions (and it's super old). We can open a new issue if someone wants to tackle this issue across body text.
