### ISSUE TITLE
Add ⚡️ `Lightning services` page to `Designing Bitcoin products` chapter

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#532]
The wallets we are focused on modelling the guide's content around (Phoenix, Breez, Muun etc.) all have great UX due to offering various 'Lightning services.' These entities that provide these are what you call 'Lightning service providers' or LSPs. I am proposing we include a page in the DBP chapter about these Lightning services and how LSPs can use them. Everything should be detailed within a design context of course. 

As we add Lightning content to the various sections of the guide it will be almost impossible to illustrate great UX flows without mentioning Lightning services. This page should do the heavy lifting on the details of these services and should be referenced to from the more practical sections of the guide (onboarding, payments etc.) similar to the `Technology primer`. 

Below is a rough outline of sections that would be in this page. All of these are pretty much interoperable except probably the warm node / backup and recovery. 

- Payment forwarding (warm node - node doesn't have to be online 24/7). 
    - Potential custodial issues with this? 
- Inbound liquidity 
- Turbo channels  
- Backup and recovery
- Route calculation 
    - Trampoline nodes
- Swaps (on-chain <-> Lightning)
- Watchtowers
- Lightning address for easy payments
- Meta LN services like LN+, Amboss, Lighting Terminal. These aren't really end user services but may be worth noting them at the bottom of the page.

**Comment by johnsBeharry** [comment]
Concept ACK. It also is a good idea to model it after the tech primer cause in a way it is similar.

Inbound liquidity*
- This may be one of the most common LSP types as it may be the first (and only) connections to lightning someone has.

Lighting Terminal
- haven't used but from what I gather is more of a management dashboard, its on the application layer instead of service layer.

Amboss, LN+
-These two can be seen as "LSP Directories", especially LN+.
- So I'd argue they are end user services as they are solving a **discovery problem** of channel partners + liquidity.
- A bitcoin application can aggregate and filter from multiple directories and filter them based on some questionnaire that captures their preferences.
- Might have some link to the software overview page though as Amboss especially in its current state at least seems similar to an explorer.

**Comment by pavlenex** [comment]
@Bosch-0 is this something we'd still want to tackle in the [Milestone #10](https://github.com/BitcoinDesign/Guide/milestone/11) or should we postpone it for later revision?

**Comment by Bosch-0** [comment]
@pavlenex How's about we include it in the next milestone so we can wrap up 10 :)
