### ISSUE TITLE
Re-consider the navigation and browsing experience

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#551]
We've had several discussions (including [yesterdays jam session](https://github.com/BitcoinDesign/Meta/issues/157)) around how the current nav structure can be confusing at times:
- Pages with the same names (for example, `Automatic cloud backup` in both `Onboarding` and `Private key management` sections)
- `Onboarding` is about a very specific type of product, `Private key management` is about underlying tech, etc. Not always intuitive why

Examples of top-level structures:
- [BTCPay docs](https://docs.btcpayserver.org): main sections are `User guide`, `Deployment` and `Development`, with additional `Explore by topic` options
- [Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/): main sections are `macOS`, `iOS`, `watchOS` and `tvOS`, with additional `Technologies` options

Two starting points:
- What content do we have, is there a better natural structure?
- What entry points do readers want (`I want to find info about onboarding UX`, `I want to understand how multi-key works`...)

I am wondering if we should bundle `Onboarding` and `Payment` into a single mega `Daily spending` case study. It is pretty much a more elaborate version of the other case studies we have. I think the best way to resolve this task is by mocking things up in Figma.

**Comment by Bosch-0** [comment]
I've wanted to bundle Onboarding + Payments for awhile and think this makes a lot of sense compared to the current structure - big ACK from me.

I like the idea of having a more intuitive landing page for the guide, kind of how BTCPay docs and Apple human guidelines initial view is. Some example sections we could have displayed in a similar manner to the Apple human interface guidelines:

- Getting started (Jumps straight to start of the guide. This would be targeted at designers new to Bitcoin and want to read the Guide from start to finish rather than jump into the meat and potatoes / practical sections of the Guide). 
- Daily spending (focuses on Lightning first, mobile, non-custodial wallet application design)
- Savings (Focuses on multi-key, cold storage application design)
- Resources? (For all the supplementary / underlying tech chapters)

If we go with this structure and have the main sections of the guide essentially case studies, do we really need the `Case studies` chapter? 

We should also have a search as well as some suggested topics on this landing page for easier navigation. 

Another suggestion is having section headings in the sidebar nav like BTCPay has below:

![image](https://user-images.githubusercontent.com/55287964/140006554-23b6d1ed-bba4-4c23-84b8-2326e09cf1e1.png)

I will do up some mockups for my above suggestions to explain this more clearly.

**Comment by Bosch-0** [comment]
Relevant Figma brainstorming file for this issue: https://www.figma.com/file/5amvNM95DkHFpOnVzzoAyK/Guide-visual-review-210504?node-id=201%3A2

**Comment by GBKS** [comment]
We had a brainstorm session for this issue yesterday. Here are the relevant links:

- [Recording](https://youtu.be/H6KdwaLoHaU) of the session
- [FigJam](https://www.figma.com/file/g3psdWFFRzGgyQqZjLxth9/Bitcoin-design-guide-nav-rethinking?node-id=0%3A1) used in the session
- [Text summary](https://docs.google.com/document/d/15sw-45Nxuhw-1G0WsEM4Nv4CO4MNzMsrna13cfXYjGE/edit?usp=sharing) of the proposed changes
- [Video summary](https://youtu.be/FLWJ_VhnSzI) (10 minutes) of the proposed changes

And here's a visual summary, comparing the current and proposed landing pages (this is discussed in the summary video above).

<img width="3232" alt="Bitcoin design guide change summary 220314" src="https://user-images.githubusercontent.com/695901/158544280-31e0d0bc-d7ba-4f52-8b35-0638548320cf.png">

Next step is to run this past the community and get more feedback. We also want to have a call to invite people to share their ideas. Then we'll revise the plan again and try to implement this in logical steps (inviting feedback again with each step).

**Comment by GBKS** [comment]
See [milestone #15](https://github.com/BitcoinDesign/Guide/milestone/16) for issues that came out of these discussions.

**Comment by GBKS** [comment]
Wrapping up milestone #15 now. A few remaining issues were not completed, but instead split into new issues, or will be tackled separately in other milestones.
