### ISSUE TITLE
Create a case study on spaced repetition recovery phrase reminders

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#599]
We should add a suggestion to the `Backing up a wallet,` page and maybe other areas, around spaced repetition backup reminders. Firstly, what is spaced repetition? From Wikipedia: https://en.wikipedia.org/wiki/Spaced_repetition

> Spaced repetition is an evidence-based learning technique that is usually performed with flashcards. Newly introduced and more difficult flashcards are shown more frequently, while older and less difficult flashcards are shown less frequently in order to exploit the psychological spacing effect. The use of spaced repetition has been proven to increase rate of learning.

Replace flashcards with backups and that is the idea. Signal messenger does this with their registration lock feature so users don't forget their PIN. Users should be regularly reminded of the importance of their backups and how they operate. This concept should he heavily ingrained into bitcoin holders minds and spaced repetition is a good way to achieve that. Some questions to ask / things to remind users of with these periodic reminders could be:

- How important it is that their backups are securely stored.
- That they may want to test their backups to ensure they work properly.
- Re-iterate that if their backup is lost and they lose their device their bitcoin is gone forever.

These questions could be asked and followed by a simple 'I understand' CTA. For the test back up question users could be re-directed to a backup testing flow within the application.

Thoughts? 

![breakingbad-science](https://user-images.githubusercontent.com/55287964/147190004-96bf158d-6a00-4fc4-8193-d8404d755106.gif)

**Comment by glowang** [comment]
Hey @Bosch-0 , I love this idea! I'm new to the design community but would be down to jam on this.

**Comment by Bosch-0** [comment]
Sweet! Assigned you and myself, crated a Google doc we can start collecting my thoughts around this :) https://docs.google.com/document/d/1uBQ-JMmbyvd1iUNFC6fMqf6Z3GUqpq74rceAIdB2jA8/edit?usp=sharing

**Comment by Bosch-0** [comment]
Rather then add this to a reference design this could be an interesting case study / research report. Would you still be interested in working on this with me @glowang? @mouxdesign you may be interested too.

**Comment by mouxdesign** [comment]
Thanks for tagging me in this @Bosch-0. Personally I too am a fan of spaced repetition and do see it as being something that would be very useful to help users understand the importance of certain things. Will have a look at the word document and provide some feedback there. Happy to help create a case study on it as well.

**Comment by pavlenex** [comment]
We can add a one-line explanation of the spaced repetition in this section here https://bitcoin.design/guide/daily-spending-wallet/first-use/#security-reminders just a brief mention?

**Comment by yashrajd** [comment]
I was working on creating a copy draft for this issue when I noticed a one-line explanation seems to already have been added here https://bitcoin.design/guide/daily-spending-wallet/security/#reminders--recommendations (also seems to be a better location than the First Use section.)

Will this issue be closed now?

**Comment by yashrajd** [comment]
Dropping a draft of the copy I was working on (feel free to repurpose, remove or delete if unhelpful) since it exists now:

It may be a good idea to incorporate [spaced reminders](https://bitcoin.design/guide/daily-spending-wallet/security/#reminders--recommendations) to inform users and encourage them to achieve robust security of their funds.

//include examples
–	security status checklist
–	PIN/password reminders if touchID/faceID are set up
–	wallet backup reminders
–	recovery-phrase flash cards
–	passphrase reminders
–	general tips & warnings

//include triggers
–	events like receiving funds, funds threshold
–	actions such as app launch/restart, setting up a new wallet
–	duration/frequency like once every day/week

**Comment by yashrajd** [comment]
Find the working document here: https://docs.google.com/document/d/1SM-r6M2fYVaKnb8zTw7fzvOUySd1EwAxvR7AbDtF0EU/edit?usp=sharing

**Comment by GBKS** [comment]
I just took a look at the Signal code, since they regularly remind me to enter my PIN to see if I still know it. I found the logic [here](https://github.com/signalapp/Signal-iOS/blob/1b5691e019dee0d56eff13f95d9331fe0e001df7/Signal/src/Experience%20Upgrades/Upgrade%20Views/PinReminderMegaphone.swift#L35). Looks like the remind you after 1, 3, 7, and 14 days. The code for the modal itself is [here](https://github.com/signalapp/Signal-iOS/blob/ccb1e46ac1b9d2c527d9e691f9862faef33146df/Signal/src/ViewControllers/OWSPinReminderViewController.swift). The copy shown to the user to explain the feature is [here](https://github.com/signalapp/Signal-iOS/blob/e328e4bf8ae355f6a276b3d3ac5f2dac3bd5c3e6/Signal/translations/en.lproj/Localizable.strings#L4757). Some of the lines:

- `To help you memorize your PIN, we’ll ask you to enter it periodically. We’ll ask less over time.`
- `We’ll occasionally ask you to verify your PIN so that you remember it.`
- `We’ll remind you again tomorrow.`
- `We’ll remind you again in a few days.`
- `We’ll remind you again in a week.`
- `We’ll remind you again in a couple of weeks.`

And there's a [setting](https://github.com/signalapp/Signal-iOS/blob/1b5691e019dee0d56eff13f95d9331fe0e001df7/Signal/src/ViewControllers/AppSettings/Account/AccountSettingsViewController.swift#L222) in options to enable or disable the reminders.

![IMG_3422](https://user-images.githubusercontent.com/695901/214247851-cd33002f-0e66-4c78-8322-5104806d93ac.PNG)

Here's the [Signal help section](https://support.signal.org/hc/en-us/articles/360007059792-Signal-PIN#pin_reminders) with info about PIN reminders.

Would be fairly easy to integrate this setting and some of the language in the UI Kit and then add mock-ups to the [Security page](https://bitcoin.design/guide/daily-spending-wallet/security/#reminders--recommendations).

Is this helpful?

**Comment by yashrajd** [comment]
Thank you, overall agree. Would consider maybe adding that last bit to the Settings/Security section?

Tasks for me from your comment:

- add copy examples to doc
- create mockup with examples?
- create setting mockup

**Comment by mouxdesign** [comment]
Added in some copy suggestions to this one. Good job @yashrajd

**Comment by GBKS** [comment]
I created PR #994 for this, trying to add precisely what we discussed here without bloating the page. Please take a look.
