### ISSUE TITLE
Units & Symbols - Add guidance for case where amount is less than smallest fiat unit

### ISSUE THREAD

**Issue by danielnordh** [BitcoinDesign/Guide#627]
Values in satoshi can sometimes be less than the smallest fiat unit, making the display of the value in fiat difficult.
We should add guidance for how to deal with this on the [Units & Symbols page](https://bitcoin.design/guide/payments/units-and-symbols/).

**Fiat transactions**
Fiat to bitcoin: Show fiat value + bitcoin value down to accurate satoshi
For example: $10, 25,774 satoshi, 0.00025774 bitcoin

bitcoin to fiat: Show bitcoin value down to accurate satoshi + fiat value with the detail that counterpart actually supports 
For example: 100 satoshi, $0.038878830, ~$0.039, ~$0.04 (this would not work), ~$0.03 (this would have a surplus of $0.008878830, or ~25 satoshi if the fiat service only supported full cents)

What happens here if there is a 'surplus' of satoshi beyond the smallest supported fiat unit (even though officially it is $0.01, individual companies' systems might support more decimals), but not enough to reach the next cent?
Should the service automatically adjust, returning the surplus?

**Lightning only transactions**
In situations no fiat is involved it is still valuable to be aware of differences in more detail, so showing more decimal positions can be useful. For example when paying fees, it might make sense to know the order of magnitude difference.

On Jan 21 2022, these are some example values:
1 satoshi = $0.00038878830,  ~$0.00039, $0.0004
10 satoshi = $0.0038878830, ~$0.0039, $0.004
100 satoshi = $0.038878830, ~$0.039, $0.04

Originally raised by @moneyball on Slack.

**Comment by HarshKumarChoudary** [comment]
Could you please assign me to this task. I think I can do some contirbution to it.

**Comment by GBKS** [comment]
Here's what I'd do:
$0.3 -> $0.30 (at least 2 digits because cent is based on 100)
$0.03 -> $0.03
$0.003 -> $0.003 (always show the digit if lower than 1/100)
$0.0003 -> $0.0003

And:
$0.38878830 -> ~$0.39 (round to two non-zero digits, add `~` to indicate rounding)
$0.038878830 -> ~$0.039 (always show the two digits)
$0.0038878830 -> ~$0.0039
$0.00038878830 -> ~$0.00039

There is a point where the amount is so tiny that you might as well say it's zero ($0.000001). This is not too dissimilar to on-chain dust, which are amounts smaller than the fee incurred for transacting them. Not sure where you'd draw that line, probably at an arbitrary number of digits (how about 6).

I tested the [browser functionality](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat#using_options) for formatting currencies, but that always rounds to cents and is therefore not helpful.

**Comment by GBKS** [comment]
This was completed with #709.
