### ISSUE TITLE
Add generic icon example for UI toolkit annotated transactions

### ISSUE THREAD

**Issue by moneyball** [BitcoinDesign/Guide#660]
For payments in which we do not have a logo or even a name (such as Motor City), let's show a recommended generic icon to use in the payment list. One suggestion is to just show a bitcoin logo. https://www.bitcoinuikit.com/screens/screen/transactions-annotated-transactions

**Comment by GBKS** [comment]
I can tackle this together with #661.

A simple default could also be an up or down arrow to indicate whether bitcoin was sent or received.

**Comment by Bosch-0** [comment]
I like using a more fun icon, the bitcoin icon is a good default. I like how Breez uses the alien icon. 

I think the amount can be colorized to communicate if it was sent or received as well as have a + or - next to that amount to communicate that even further In Zeus we'll be using a custom icon of Harpocrates - the greek god of silence and confidentiality for this.

**Comment by GBKS** [comment]
I personally prefer a subtle approach to this. Using the bitcoin icon adds visual noise and distracts. The [Jazzicons](https://github.com/danfinlay/jazzicon) are also visually really prominent and can dominate the screen, so I'd also be very deliberate about deciding whether to use them. The activity screen is a place where a user wants to quickly browse a data set to see what's new, find something specific, identify patterns, etc. So I'd avoid adding anything that adds visual interest without signal (unless it is deliberate, like you want to add some quirkiness to your app by using Alien icons like Breez).

Some decisions I made in the [design that's live](https://bitcoin.design/guide/payments/activity/#what-is-a-transaction):
- Sent amounts do not need to be red (or another color), it's enough to highlight received amounts in green (positive connotation).
- Adding a plus/minus is necessary next to the amount for the color-blind (and just general readability/usability).
- Tried to keep the fallback icon useful, indicating whether bitcoin was sent or received, and the status of the transaction. It subtly repeats information already embedded in the other elements. When it's not shown because there's a contact image, no information is lost.

I can add some more detail to the page.

**Comment by moneyball** [comment]
Yes it'd be great to elaborate on the thinking in the UI toolkit in text in the design guide as you've done above in the bullet points.

**Comment by Bosch-0** [comment]
> Sent amounts do not need to be red (or another color), it's enough to highlight received amounts in green (positive connotation).

How would you display a channel open? In Zeus we have them as white, outbound - with red copy, inbound + with green copy. 

Completely agree the icon should be useful. Though disagree that the bitcoin icon would be visual clutter, it can just be used a placeholder for a unknown which can nudge the user towards adding that payee as a contact. Or you could just use something like below to make that more clear though. 

![image](https://user-images.githubusercontent.com/55287964/154444749-21bbefd0-5744-4898-ab27-5ed629822a62.png)

The Jazzicons have a bit too much pezas for my liking, something more minimal like https://github.com/stewartlord/identicon.js/ when using identicon's would be my recommendation.

**Comment by GBKS** [comment]
> How would you display a channel open? In Zeus we have them as white, outbound - with red copy, inbound + with green copy.

Personally, I prefer to only use red when something actually went wrong. It's a strong signal color. A list like this quickly turns into a mess if every item gets a unique treatment, so I'd keep it all very subtle.

I assume that some users will simply not care about organizing things. If there's a static placeholder, they will always see it, over and over. So I'd rather create a fallback that communicates something.

But these types of decisions can be made very differently based on your design style, brand voice, etc. That's why I am sometimes a bit hesitant to include highly specific design recommendations in the guide. Overall, I think the visual recommendations in the guide should be fairly timeless and universal, and then individuals designers can more easily add their own touches to them.
