### ISSUE TITLE
Provide UX guidance for showing payment history

### ISSUE THREAD

**Issue by moneyball** [BitcoinDesign/Guide#661]
I don't see anywhere in the guide currently to provide guidance on how a wallet should display payment history. This is an important part of a wallet and should definitely be in the guide. The UI toolkit does address this, so how about we add a section in the guide, show these screens and add some additional copy to describe the thinking that goes into the payment history?

https://www.bitcoinuikit.com/screens/screen/transactions-transaction-list
https://www.bitcoinuikit.com/screens/screen/transactions-annotated-transactions
https://www.bitcoinuikit.com/screens/screen/transactions-transaction-list-grouped

**Comment by GBKS** [comment]
I've gone through a lot of iterations on this for the UI Kit, and started thinking about this as "Activity" instead of a "Payment history". This allows the list of events to include more than just payments, based on the unique features the wallet offers. For example:

- Breez can show subscriptions to podcasts
- Blixt can show manual channel opens/closes
- Hexa can show creation of additional accounts
- Pinned entries at the top with security reminders, multi-sig transactions awaiting signatures, etc

We should also include filter and export features (Breez has this), for anyone who needs to track transactions in external tools (or wants to close a channel and not lose the transaction history).
