### ISSUE TITLE
Add content about guiding users towards using lightning

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#678]
One specific thing that we need to cover is handling situations where the user needs to be guided towards to making a Lightning payment instead of an on-chain payment.

For example, perhaps the user is using a Lightning-only wallet (like Breez) but the receiving party gives them an on-chain address. Or the user is using a wallet that supports Lightning as well on-chain (like BlueWallet), but it's more beneficial (cheaper and faster) for the user to use Lightning. Or consider a wallet like CashApp, where the on-chain send actually has a minimum amount defined.

A BIP21 payment link with lightning invoice included is great solution to this problem, but only works in situations where both parties wallets have adopted this idea. I think wallets should provide some simplified guidance on how to proceed in situations like these.

If the user accidentally scans an on-chain address, we need to help them find a better way to pay.

**Comment by sbddesign** [comment]
📝 [Early rough draft on this idea](https://docs.google.com/document/d/1ePsl6gMB5Diq09ozG1jRWyw7zJGIFTTzd7ZFWRoDyhM/edit?usp=sharing)

**Comment by moneyball** [comment]
If we expect wallets to read the guide and make a change why don't we just
recommend them to support a single qr code to solve the problem entirely?
Likely less work than whatever this PR will suggest.

**Comment by moneyball** [comment]
Also there will be copy/paste UIs with on-chain addresses and LN invoices even in a world with ubiquitous single QR codes.

**Comment by sbddesign** [comment]
@GBKS and @Bosch-0. What would you think if I merged some of the content in the [above Google doc](https://docs.google.com/document/d/1ePsl6gMB5Diq09ozG1jRWyw7zJGIFTTzd7ZFWRoDyhM/edit?usp=sharing) into the [Sending Bitcoin](https://bitcoin.design/guide/daily-spending-wallet/sending/) page?

For refresher: ideally, everyone uses a BIP21. Until then, there's going to be situations where a user is given an on-chain address and it seems prudent to have some messaging that this transaction might take longer to clear.

**Comment by sbddesign** [comment]
My thinking is this would go in or under the "Review and approval" section.

**Comment by Bosch-0** [comment]
Sounds reasonable to me, just some thoughts 

> For example, perhaps the user is using a Lightning-only wallet (like Breez) but the receiving party gives them an on-chain address.

This scenario would be better addressed in the [error section](https://bitcoin.design/guide/daily-spending-wallet/sending/#errors). Sending an on-chain payment from a wallet like Breez isn't possible. So entering one should be accompanied with a easy to read error that guides the user to requesting a lightning payment from the requester instead.

> Or the user is using a wallet that supports Lightning as well on-chain (like BlueWallet), but it's more beneficial (cheaper and faster) for the user to use Lightning. 

One thing we we should address in [milestone #16 ](https://github.com/BitcoinDesign/Guide/milestone/17) is limiting the on-chain components of this section and honing in on lightning-first / LSPs / other lightning service components. On-chain should only be mentioned in the context of swaps / rare channel close scenarios. This is how I envision daily spending wallets. 

So instead of addressing this within the context of a wallet like Blue, we address it in the context of one like Phoenix that uses swaps for on-chain payments. In this case the fees would be much higher and be addressed like you've laid out in your doc but slightly different - swaps may be even slower in some scenarios / involve some trust possibly. 

We are in this kind of limbo area with the DSP between a wallet like Blue and Phoenix but we should be leaning more towards Phoenix imo.

**Comment by GBKS** [comment]
I like it. It's generally a good idea to add this type of contextual help that makes it easier for users to make good decisions. Better than relying on them to "read the manual". It signals that the app looks out for them, and they will be more comfortable using it, and less afraid of making mistakes. Getting the wording right will be essential.

Are you aware of any wallets that already do this?

**Comment by sbddesign** [comment]
> Are you aware of any wallets that already do this?

No -- I opened the issue specifically because I witnessed wallets not doing this.
