### ISSUE TITLE
Proposal to rename this repository from "Guide" to "Website"

### ISSUE THREAD

**Issue by pedromvpg** [BitcoinDesign/Guide#7]
As of today, we're including the guide as a part of a website which will include other sections: projects, contribute, and more in the future.

Do we want to consider encompassing everything under a "website" repository? Or is it better to keep the guide separate?

I think for now, as we grow the content from nothing, it would make sense to have everything under one roof, and then separate if it becomes much much bigger and justifies multiple repos.

**Comment by ConorOkus** [comment]
I think this makes sense and is more accurate given what the site will represent in the long term. The design guide is part of the website. I would maybe update/add a new project for just the guide content then instead of having a content project as that could include non-design guide content, maybe that's okay though.

**Comment by ecurrencyhodler** [comment]
I don't think we should change it. The Bitcoin Design Guide and the website should have their own dedicated repos. Although it sounds like we've settled on a single domain(which I'm in favor of), separating the two makes the most sense. 

For example, the website repo could include agendas from the community discussions as well as elements from the Bitcoin Design Guide.

**Comment by pedromvpg** [comment]
As in other aspects of this project, we can start with a single repo and separate it overtime as it scales. 

For now we could mostly focus on growing the content and as it becomes bigger, then we can separate and grow into separate repos and projects.

**For launch**

- /BitcoinDesign/Meta
- /BitcoinDesign/Website

**In the future**

- /BitcoinDesign/Meta
- /BitcoinDesign/Website
- /BitcoinDesign/Guide
- /BitcoinDesign/Projects
- /BitcoinDesign/Experiments
- /BitcoinDesign/DesignSystem
- ...

**Comment by ecurrencyhodler** [comment]
I don't think we should immediately conflate general content with the Bitcoin Design Guide repo. It will make it confusing for people to contribute to. The Bitcoin Design Guide is it's own project and should be considered independently from other content people might propose such as UX studies or UX research.

**Comment by GBKS** [comment]
If those repos are split, would the Jekyll setup also be duplicated? Meaning that all CSS/JS/templates/etc are in two places? If that's the cases, I'd just be worried about an overly complex workflow.

I have no strong opinion on naming.

**Comment by ConorOkus** [comment]
Perhaps the content project can have labels for each issue `Design Guide` `General Website` etc. Then contributors can open a pull request which in most cases will be a markdown file and link it to that issue?

**Comment by johnsBeharry** [comment]
Since this issue has been open there hasn't been any strong mention to rename the repo.

So I'll be closing off this issue in 3 days if there are no further comments.

---

NACK. Personally I'm in favour of keeping it as Guide as there are discussions relating research for different sections of the guide. At this point it may also require a few more links/references to be updated than when the issue was posted (17 forks).
