### ISSUE TITLE
Create `Case Studies` section

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#722]
Create a “Case studies” section, for analysis of external products (a la Built for mars). We don’t have content for this yet, so this task can wait.

This is an idea that came out of our [brainstorming session](https://docs.google.com/document/d/15sw-45Nxuhw-1G0WsEM4Nv4CO4MNzMsrna13cfXYjGE/edit#heading=h.x28s45jtix44) on re-organizing the Guide content.

**Comment by GBKS** [comment]
Case studies could also be:

- Project stories (how Alby grew from a hackathon project, how collaboration around the videos for Hello Bitcoin worked, etc)
- Bitcoin Design Sprint retrospectives
- A UX research report (including process, data and interpretation) that doesn't fit elsewhere
- Retrospective for a campaign like [bitcoinqr.dev](https://bitcoinqr.dev)

What else?

**Comment by Mogashni** [comment]
Really like this idea and Christophs suggestions to make the content broader than just typical case studies. I think that  once we see just how much content goes into here then we can further divide it. Personally I am working on putting together a case study for the Blixt design sprint so this would fit in well in this new section.

**Comment by Bosch-0** [comment]
Thor's work could get this started

**Comment by mouxdesign** [comment]
Have created an initial case study for Blixt to add to this section. Would love some feedback on it in terms of the content and the structure. Tried to tell a story more to keep readers engaged and wrote it in the hero's journey format.

![Artboard (2)](https://user-images.githubusercontent.com/90313394/188474397-def2e5b6-1198-4d73-b635-a90051349776.jpg)

# How do we help new users to open lightning channels?
Blixt Wallet is a non-custodial open-source Bitcoin Lightning Wallet for Android and iOS with a focus on usability and user experience.

> ## Blixt is has a goal of serving users who new to lightning but are familiar with bitcoin but want to try out the lightning network for the first time. The current userbase of Blixt tend to be more advanced users and Blixt would like to move towards catering more for users who want to try out the lightning network as well. 

## What does Blixt do?

- Onboard someone quickly over lightning so they can have a channel already provisioned to receive funds

- Automatically open channels anytime the user has on-chain funds (Auto pilot)

- Automatic channel creation during initial deposit of funds

- Support for custom LSP

![Group 2417 (2)](https://user-images.githubusercontent.com/90313394/188487988-f1217f94-8a64-432a-88bb-43c7ad7d5657.jpg)

![Group 2418 (3)](https://user-images.githubusercontent.com/90313394/188488150-29f0a366-b709-48e7-b65e-3f2de8230cda.jpg)

Since Blixt is an open source wallet we collected user research simply by going on their Discord channel and collecting comments and questions from users.

> # We discovered that Blixt users were mostly struggling to open lightning channels.
We created alot of different user flow to find a solution for the best method to open a channel for a user new to lightning, and eventually settled on this one.<br/>
![Group 2356](https://user-images.githubusercontent.com/90313394/188488483-e418adcf-801f-4e88-93ea-db06139d1145.jpg)

> # One of the biggest challenges we faced was…

- Providing enough education in the userflow to educate new users about channels and using language that would be easy and simply for them to understand. 

- After re-designing the interface we tested the new design by doing some usability tests.

> # Here’s what we learnt…

- Users new to lightning are missing a crucial step, the why. They need to understand why they need to open up a channel before being presented with the screen to set up the channel. Once this is clear it becomes easy for a user to understand that this step is necessary before transacting.

- Telling users how long it will take to set up a channel, sets nice clear expectations around how long  the process will take, this can perhaps be done right at the beginning as well.

Opening channels is something unique to lighting wallets and an essential first step during the onboarding process. For users completely new to lightning, opening a channel in itself is something that is new and unique to them. It is then nice to explain to users the reason as to why a channel should be opened prior to presenting them with the channel opening screen. An example of the text could read:

Explaining the concept of opening a channel to a user that has never used a lightning wallet

_“First things first to use your lightning wallet, you’ll need to set up a channel. Think of a channel as your electricity connection to the lightning network. By opening a channel you are able to make transactions.

To open a channel first we will need to add some bitcoin to it. Once that is done you will be ready to make your first transaction.”_ <br/>
![Presentation Mobile](https://user-images.githubusercontent.com/90313394/188489007-c85fba65-e9d7-4841-9a1c-b1971be1015e.jpg)

> # Here's what we learnt about educating users...

- Providing users with educational screenstates is a good idea, its always nice to keep the text as short as possible and keep the explanation easy as well. Through the usability testing we learnt that we could further simplify the text in this educational part.

- We also learnt that when providing educational screenstates we should also allow uses the option of going back so that they can  read the text from the previous screen. <br/>
![Group 2409](https://user-images.githubusercontent.com/90313394/188489603-af2a1c22-42ce-4423-816b-e33b8881a050.jpg)

<br/>

Link to [googledoc](https://docs.google.com/document/d/199BOVnTFpseWmiOWm2wyj1D1bfkSrTENGlESV2ii0YM/edit?usp=sharing), feel free to comment there.

**Comment by pavlenex** [comment]
Great effort here @mouxdesign, will take a review on this if it's still needed.

**Comment by mouxdesign** [comment]
@pavlenex Yes would really appreciate a review!
