### ISSUE TITLE
Create a banner image for the `Payment request formats` page

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#742]
**Request the visual**

Hello, I would like to request a visual for the payment request formats section of the guide.

**Link to the page**

https://bitcoin.design/guide/how-it-works/payment-request-formats/

**Visual Type**

Header banner image. 

**Illustration guidelines**

If you're a contributor looking to tackle the issue, you can [preview our illustration guidelines](https://bitcoin.design/guide/contribute/illustration-guidelines/).

**Comment by Bosch-0** [comment]
Playing around with that [Neubrutalism](https://dribbble.com/search/neubrutalism) aesthetic, thoughts?

![image](https://user-images.githubusercontent.com/55287964/168537543-7ed78213-0a7e-4c7e-8dcb-55b770b3f33f.png)

**Comment by sbddesign** [comment]
I didn't know neobrutalism was a thing. It's fun looking.

Here's an idea I'm throwing into the ring.

![payment-request-formats-image](https://user-images.githubusercontent.com/2414177/168861443-1db77454-63ca-4afa-973c-84adf6c7eb7d.jpg)

[Figma here if anyone wants to hack at it.](https://www.figma.com/file/Vsy6Gei3fxPDCqVCb1yjsL/Payment-Request-Formats-Header?node-id=2%3A2)

**Comment by Bosch-0** [comment]
I was trying to mask the sad feels with all the bright funky colors 😆

**Comment by GBKS** [comment]
Since the content of this page is so confusing, I'd like to see a something simple that communicates the general idea - how payment info gets passed between in and out of apps. Maybe something like the banner of the [interoperability page](https://bitcoin.design/guide/designing-products/interoperability/). Could be one centrally positioned device surrounded by a couple of smaller ones. Arrows between them could indicate communication happening. Each arrow could have a small shape at the center to indicate that something slightly different is being passed along.

I like the style and meme experiments, but overall I am not a fan of putting lots of words into header images. How can we visually communicate what this page is about?

**Comment by sbddesign** [comment]
> Since the content of this page is so confusing, I'd like to see a something simple that communicates the general idea

Yeah, I like that thinking

> I like the style and meme experiments

Mine was just a dumb joke

**Comment by Bosch-0** [comment]
Yeah I agree, I just whipped up that design quickly to play around with that style. Will put some more thought into it and come back soon!
