### ISSUE TITLE
📱 Revise `Daily spending wallet` -> `Backup & Recovery` section

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#763]
This issue will be part of a bigger milestone that focuses on revising the newly formed Daily spending wallet reference design we now have in the guide.

Need to address metadata backups: https://github.com/BitcoinDesign/Guide/issues/648

**Comment by Bosch-0** [comment]
For these revision pages the images should also be  generally updated:

- Ensure they reflect what is shown in the UI kit
- Apply [new modal](https://bitcoin.design/guide/contribute/formatting/#image-viewable-in-larger-modal-with-alternate-mobile-image) formatting to images  
- Remove grey area on the iPhone 'dip' at the top of the phone (see below). 

![image](https://user-images.githubusercontent.com/55287964/163140077-2a560b16-09bc-4dcb-b468-2b8031629795.png)

**Comment by Bosch-0** [comment]
We need to address multi-language recovery phrase backups as part of this issue: https://github.com/BitcoinDesign/Guide/pull/753

**Comment by GBKS** [comment]
@sbddesign you think it makes sense to split this issue into 4 separate ones? One for each of the pages?

**Comment by sbddesign** [comment]
I've been doing more work on this for #856, focusing on the recovery flows this time.

## Figma

Looking for feedback [on this work here](https://www.figma.com/file/q9EgLqOKcIVc0Cq7khtpNm/Onboarding-%3E-Backups?node-id=450%3A3292).

![Screen Shot 2022-07-19 at 11 18 57 AM](https://user-images.githubusercontent.com/2414177/179787527-eb0e32b0-3efb-460e-9c7e-f59d6518344f.png)

## Video

[Here's a video](https://youtu.be/gVEB2AXGKrs) of me narrating my thoughts over the Figma file. It ended up being long, so if you're interested in watching, save yourself the trouble and pop it on 2x speed, or use the timecodes in the notes to skip around. Notes below:

## High level overview

- Recovery scenarios
  - Basic Recovery - this is for non-hostile scenarios, like the user losing their phone or replacing the phone with a newer one.
  - Emergency recovery - this is for hostile scenarios, such as app provider or LSP becoming evil, censorship, or technical/business problems on part of app provider or LSP.
- For this particular product, all that's needed is:
  - Recovery phrase
  - Channel state
- Manual backup means manually backing up _the key_
  - Obviously it's for advanced users
  - It **does not** mean manually backing up the channel state -- such backups will almost always be out-of-date and so would harm the user's access to funds in a recovery scenario
  - An advanced user might opt-out of using the stock auto channel backup location (say, store in NextCloud instead of Apple), but we must assume that there will be some form of cloud backup for the channel state in all scenarios.
- Recovery tool
  - There should be a sovereign recovery tool that can be published independently of an app store
  - This could be useful for an emergency recovery scenario, particularly one where an app has been pulled from the app store
  - This sort of content could be applicable beyond just the daily spending wallet, so maybe recovery tool info could go on another page
  - Recovery tool could potentially restore access to funds without channel state by asking LSP to force close. Good to have this option for an emergency, but this would not work in a scenario where the LSP is offline or uncooperative.

**Comment by sbddesign** [comment]
Thanks for leaving feedback on the Figma, everyone. I've been making some revisions to the frames and also laying out updates inside of a Google Doc. I'm trying to make sure that I avoid redundancy and keep all the content relevant to _this specific daily spending wallet._ Working with all the content inside a single document is helpful to this end.

https://docs.google.com/document/d/1CfeIfygTdTWTm6I61iIlEYI8RPE58UjTmIoAB4DeG5A/edit?usp=sharing

I'm not quite ready for feedback on it, but will be very soon. Then we I can start turning that into commits for #856.

**Comment by sbddesign** [comment]
Update: I am ready for feedback on [this document](https://docs.google.com/document/d/1CfeIfygTdTWTm6I61iIlEYI8RPE58UjTmIoAB4DeG5A/edit?usp=sharing).
