### ISSUE TITLE
Brainstorm a first table of contents for a new merchants section

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#788]
As discussed in [jam session #24](https://github.com/BitcoinDesign/Meta/issues/260), there is interest in creating a merchant section. To get this effort off the ground, a good exercise would be to brainstorm what content to include. This will also help us decide what not to include, what to prioritize, etc. This is similar to what we did at the beginning of the guide project.

Join the discussion in the [#merchants](https://bitcoindesign.slack.com/archives/C03C2CHHENA) channel on Slack. We have a Google Doc floating around to gather ideas.

**Comment by sbddesign** [comment]
I think this issue has sort of been tackled [here](https://docs.google.com/document/d/1FY2yMtAu4prxlWT280K8Sd_zkvrm1UkypVTnt5jFzLA/edit?usp=sharing).

Of course, the document is subject to change, commentary, and further edits. But it has been sitting in the open for a long time and doesn't really get any pushback.

@GBKS Should we consider this issue closed, since the issue is merely to "brainstorm a first table of contents"?
