### ISSUE TITLE
Add 2 new research links to the `Design research` page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#793]
First one is from 1,800 interviews with Salvadorean households on their bitcoin usage.
[Tweet](https://twitter.com/jp_koning/status/1519368796053639169)

Second one is about understanding how women outside the U.S. who never engaged with bitcoin feel about it.
[Tweet](https://twitter.com/spiralbtc/status/1519671312930725888) 

These should be added to the the [Design research](https://bitcoin.design/guide/resources/design-research/) page. 

Important when adding links to the [Design research](https://bitcoin.design/guide/resources/design-research/) page is to actually summarize the research and not just copy the first few lines of the document, or even the summary the researchers have provided (seen many misleading ones). Better to read for yourself and write 2-3 sentence on what the research is about, main results, and why it matters.

A second task could be to review the guide overall to see where the research could be mentioned (via link) or integrated (copy updates). I'd see that as optional.

**Comment by GBKS** [comment]
Paulo added the second link in #795.

**Comment by paulosacramento** [comment]
> A second task could be to review the guide overall to see where the research could be mentioned (via link) or integrated (copy updates). I'd see that as optional.

This could be something for me, since I will be mostly occupied with the integration/blending of research and the guide.

Besides that, I think we should also consider another way of categorisation for the different types of articles.

The distinction between _Journal Articles_, _Independent research_, _Case studies_ and _Blog posts & write-ups_ seems too vague to me.

My first instinct would be to create too categories based on number of words inside the document:

- Short format (Under X words): Perfect for blog posts and write-ups and case studies
- Long format (Over X words): More appropriate for the more academic and extensive research

What do you guys think?

**Comment by Bosch-0** [comment]
The current headings are much more descriptive. Just saying long or short format is more vague imo

Closing this btw as the two articles have been added.
