### ISSUE TITLE
📱 Create a `Daily Spending Wallet` prototype

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#800]
@GBKS, @sbddesign and myself had a call last night about how to best tackle [Milestone #16 ](https://github.com/BitcoinDesign/Guide/milestone/17). 

As we want this section to be interconnected and flow well between pages, particularly with regards to the images used, rather than individually tackle each page initially we decided to build out a comprehensive Daily Spending Wallet prototype that matches the frames in the [wallet UI kit](https://www.figma.com/community/file/916680391812923706/Bitcoin-Wallet-UI-Kit). 

Once this is done we will address the copy revisions of each page. After that, we will create a new page in the Daily Spending Wallet section that houses this prototype at the end of the section that will essentially be bringing everything together into one nice, easy to follow, prototype. 

The prototype will be built in [this Figma file](https://www.figma.com/file/1Lffm4lwEZQ3b3xlajJWYG/Daily-spending-wallet-prototype?node-id=0%3A1)

This is completely open for anyone to join in and help fyi!

**Comment by sbddesign** [comment]
Leaving a note here to remember to update [this page](https://bitcoin.design/guide/daily-spending-wallet/) once the prototype is completed.

**Comment by sbddesign** [comment]
Regarding @Bosch-0's comments on yesterday's call about making the chapters list more visual, here are some ideas.

![ChaptersVisual2](https://user-images.githubusercontent.com/2414177/189154778-c3f95852-0410-41a2-994a-172772d7b1c9.png)

![ChaptersVisual1](https://user-images.githubusercontent.com/2414177/189154779-8c5a593f-d1b8-4835-894d-b90c792871a2.png)

I prefer the second one. If we use the page heading visuals, they will not carry over well at a small size. Let's just use an icon to represent each idea and a color.

I think it's a good idea to keep the content in a somewhat linear fashion. While they can also be read and appreciated independently, they do work together to tell a story about how this product works. I think this makes more sense than a very visual grid layout.

**Comment by GBKS** [comment]
I recreated all the screens in Figma and fixed some minor inconsistencies. They are ready now to be exported so the mock-ups in the reference design are consistent. I'll do this page-by-page, starting with the first use page, and track them via a to-do list in this comment:

- [ ] First use
- [ ] Automatic cloud backup
- [ ] Manual backup
- [ ] Recovery
- [ ] Requesting bitcoin
- [ ] Receiving bitcoin
- [ ] Sending bitcoin
- [ ] Activity
- [ ] Contacts
- [ ] Security
- [ ] Privacy
- [ ] Settings

Afterwards I'll start the prototype. It will use a subset of all the screens, since some of them show alternate designs, error messages for unique scenarios, etc. So that's going to come next.

And then at the end I'll clean up the Figma file a bit more and add some documentation. We should also decide whether to publish this to Figma community or not.

**Comment by GBKS** [comment]
Oh yeah! PR #958 updates the prototype links on the landing page, and then I hope we're done with this one. It's been a beast.
