### ISSUE TITLE
PayJoin Design Challenge case study

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#969]
Yashraj took a crack at Design Challenge #6.

Here is his [research document](https://docs.google.com/document/d/16HmzGnI1620W5HqFGw2KhjqytLzByBwD4uXMKW3RFxQ/edit#) and his [FigJam flow](https://www.figma.com/file/3pJsAMrNdlRGk1U6Wqo9mp/PayJoin-User-Flow-Work?node-id=0%3A1&t=mH3EeO0WpyQMTRwQ-1).

On Jam 40, we discussed the possibility of a PayJoin article for the [Case Studies](https://bitcoin.design/guide/case-studies/) page. Opening this issue as a place to discuss this.

**Comment by yashrajd** [comment]
As I mentioned on Slack earlier today, the design challenge work is really for full critique. Perfect time to do so, feel free to critique here or on Slack.

**Comment by yashrajd** [comment]
Also slightly confused if this issue pertains to the design challenge or the case study as the label says...in my mind the challenge work is a subset of the case study.

Regardless please feel free to assign me to the issue(s).

**Comment by GBKS** [comment]
I updated the title so it's clear that this is about creating a case study.

**Comment by mouxdesign** [comment]
Update: Yashraj and I jumped on a call last week to discuss how to condense the work he has done into a case study to add to the bdg. 

We created a [rough plan](https://docs.google.com/document/d/1Pay0LzDXbYzwkWxEd9bpBdqw-2MjKckESxgi-5AuIpc/edit?usp=sharing) of how we will work together and will continue to do so. The google doc has links to:
- Google folder with all his artifacts
- Flow diagram
- UI Designs
- Original write up

Next steps:
- Mo to provide feedback on the UI designs 
- Mo to provide feedback on the user flow

@Yashraj can then start to use the [Case Study Guidelines](https://docs.google.com/document/d/1lkipBAdo-re_TCIXgMhddFpGnZU3u6f1svJ06ctjkrk/edit?usp=sharing) document to collect info he feels is relevant to include into a googledoc and then we can all provide him feedback in there. 

Yashraj please feel free to add anything in here that I may have missed.

**Comment by mouxdesign** [comment]
Quick update! 
@yashrajd and I jumped onto a call yesterday to further refine the case study doc he is working on. Together we went through the case study doc and separated the UI explanation from the case study itself. This makes the write up a lot shorter.
In the attached [Google doc](https://docs.google.com/document/d/1BN77GXs4VUOZISYK7QlyKvvFPqE7MzjOY1MHE_Qioeo/edit?usp=sharing) we discussed the next action points:

- Bullet point alot of the insights both the initial insights as well as the insights at the end.
- Action points are highlighted in orange in the doc.
Next steps is to refine the case study for readability.

**Comment by mouxdesign** [comment]
Updated [Case Study document ](https://docs.google.com/document/d/1BN77GXs4VUOZISYK7QlyKvvFPqE7MzjOY1MHE_Qioeo/edit#)which we have now refined and made shorter.

**Comment by sbddesign** [comment]
Left some comments on the doc. Looking pretty good, but there's just some parts where I'm having trouble understanding what some of the sentences say. This could be some technical background I am lacking, or could be due to sentence structure and styling. Let me know if we should get on a call sometime to discuss.

**Comment by DanGould** [comment]
Seems to me like the case study is doing lots of heavy lifting to explain the "How it works" of payjoin rather than a focus on user cases in the wild. It sounds like there might be some tension related to the contents. In review with Yashraj, I suggested a split and volunteer to draft the markdown if this direction resonates.

#### How it works &gt; Payjoin

Audience: Someone who wants an introduction to design constraints around what payjoin is and how it works.

This document may contain the *What* and the *How* of payjoin. Documenting ui interactions, flow documents, and design proposals. This details technical limitations. Which barriers are there and which can be overcome in terms of design?

#### Case studies &gt; BTCPay Payjoin 

alternative titles: Merchant Payjoin, BlueWallet & BTCPay Payjoin, Payjoin in Practice

Target Audience: Someone who knows payjoin as a concept and wants to see *why or why not* it works in practice. 

This answers: where is payjoin useful and what are the snags? Where might it develop? I think this is a better home for the explicit BTCpay & Bluewallet implementations and could house those for other implementations as well.

It might walk through the existing cases of payjoin in the wild as you've explored. The simpler one-line flows probably fit here, as do the merchant/customer studies. Constraints are focused on integration related to consumer/business process and habits rather than technicals.  Perhaps this wraps up with insights, including that payjoin is not only a privacy tool for merchants (I think lightning makes more sense in that setting) but also a [utxo management](https://blog.bitgo.com/utxo-management-for-enterprise-wallets-5357dad08dd1) tool for enterprise wallets. At least, that's the insight I have after after a focus on payjoin's place in the privacy problem.

**Comment by yashrajd** [comment]
Updating the google doc to follow: https://docs.google.com/document/d/1ydQv5SzLgXgVUNCiMXWS1zIGNAQ-wpg0-8scT33MJRg/edit?usp=sharing

**Comment by yashrajd** [comment]
Thanks @DanGould (and @sbddesign ) for offering help with drafting the markdown, I might need it badly! Really humbled by the interest and helping hand from the community, hopefully this is something useful for many people.

While I see 'the one doc does not have to do everything', I'd suggest 'not every doc/thing needs to be done now'. Might be a good idea to just get the case study outta the door?

> Seems to me like the case study is doing lots of heavy lifting to explain the "How it works" of payjoin rather than a focus on user cases in the wild. It sounds like there might be some tension related to the contents. In review with Yashraj, I suggested a split and volunteer to draft the markdown if this direction resonates.
> 
Yes @mouxdesign suggested it too and that made the case study better!. I've hived off content into multiple Google Docs as a result. Eg. [Probing PayJoin Prototypes](https://docs.google.com/document/d/1laHP3TqU6zzf0ajpQfQ5qaP0wUUQXNNnoMvVrVVU7K0/edit?usp=sharing) (probably good for the How it works > PayJoin page in the Guide).

> #### How it works > Payjoin
> Audience: Someone who wants an introduction to design constraints around what payjoin is and how it works.
> 
> This document may contain the _What_ and the _How_ of payjoin. Documenting ui interactions, flow documents, and design proposals. This details technical limitations. Which barriers are there and which can be overcome in terms of design?

Good scheme for the page in the Guide.

> #### Case studies > BTCPay Payjoin
> alternative titles: Merchant Payjoin, BlueWallet & BTCPay Payjoin, Payjoin in Practice
> Target Audience: Someone who knows payjoin as a concept and wants to see _why or why not_ it works in practice.

See [Petting PayJoins in the Wild](https://docs.google.com/document/d/1_de2pkMREGpZQwOefQdH-MZNSUPazObgRK1cruiWBmo/edit?usp=sharing) which details the analysis of live payjoin implementations.

> This answers: where is payjoin useful and what are the snags? Where might it develop? I think this is a better home for the explicit BTCpay & Bluewallet implementations and could house those for other implementations as well.

> It might walk through the existing cases of payjoin in the wild as you've explored. The simpler one-line flows probably fit here, as do the merchant/customer studies. Constraints are focused on integration related to consumer/business process and habits rather than technicals. Perhaps this wraps up with insights, including that payjoin is not only a privacy tool for merchants (I think lightning makes more sense in that setting) but also a [utxo management](https://blog.bitgo.com/utxo-management-for-enterprise-wallets-5357dad08dd1) tool for enterprise wallets. At least, that's the insight I have after after a focus on payjoin's place in the privacy problem.

I've mentioned/hinted at all of the above in the intro, insights sections after our chat that day. But you're right, they deserve a much deeper look but also need much more work.

**Comment by GBKS** [comment]
Considering we merged #993 and put the case study page live, can we close this issue? Or are there some follow-ups to do? I haven't checked, but maybe there are a few opportunities to cross-link to the case study in other pages, etc.

**Comment by yashrajd** [comment]
Great idea, I think there is scope to mention payjoin and cross-link the case study on the How it works > [Wallet privacy](https://bitcoin.design/guide/how-it-works/wallet-privacy/#bitcoin-network) page and perhaps a couple other places too. I'll tackle that at a later date.

 I think the mandate of this issue is fulfilled, and agree this issue can be closed.

**Comment by GBKS** [comment]
Thanks for the update. I'll close this issue now. Thank again for this great case study.
