### ISSUE TITLE
Custodian definition

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#990]
It might be helpful to add a definition of "custodian" or "custodial" to the glossary.

**Comment by moneyball** [comment]
I don't think this is possible because there isn't clarity from regulators and there are many jurisdictions. I also don't think the design guide should weigh in on legal/regulatory matters.

Perhaps instead the design guide should describe the trust spectrum and how different design choices increase or decrease trust in 3rd parties.

**Comment by sbddesign** [comment]
In this case, a trusted 3rd party that has the ability to prevent the user from spending their funds.

**Comment by sbddesign** [comment]
Turns out we already have a definition here, it's just "custodial" instead of "custodian".

https://bitcoin.design/guide/glossary/wallet/#non-custodial--custodial-wallet
