### ISSUE TITLE
Explore and document how to handle send fees

### ISSUE THREAD

**Issue by steynviljoen67** [BitcoinDesign/Guide#997]
**Describe your content request**

When a customer sends bitcoin to another wallet, fees can be included within the amount you want to send or on top of the amount. There are some slight nuances that creates a bad experience.

This request is to explore and document what the different alternatives are.

**Link to the page**
Still to be determined

**Why would you like to change the content?**
We currently don't have this documentation in our guides

**Suggestions**
No suggestions yet

**Additional context**
This request came up in the General channel: https://bitcoindesign.slack.com/archives/C014J9ZKXB4/p1678778610650009

**Comment by yashrajd** [comment]
@steynviljoen67 An example of service provider(s) fees that we discussed: https://twitter.com/bitcoinkeeper_/status/1634953589620891648 

These would factor into the considerations for our scenarios.

**Comment by steynviljoen67** [comment]
Great, thank you!

**Comment by mouxdesign** [comment]
Adding the [draft](https://docs.google.com/document/d/1xwLx3wFlfRsEM115nyFfjyx1aFbPcco_WsEp-_uFmgI/edit#)

**Comment by GBKS** [comment]
@yashrajd did you meant to post your comment on issue #989? Seems more relevant there.

**Comment by steynviljoen67** [comment]
Cool, I'll put some screens together and circulate for feedback.

**Comment by GBKS** [comment]
Quick update on this issue. @steynviljoen67 is pretty swamped right now so I'll help wrap things up. After reviewing all the work done, I'd recommend that we extract the [Fees section](https://bitcoin.design/guide/daily-spending-wallet/sending/#fees) in the `Daily spending wallet` -> `Sending` page into a separate sub-page. There's already a good amount of information there that we can add Steyn's research to. That will give us a dedicated page for anything related to fees, both onchain and lightning. This is more convenient for readers, and allows us to dive into more detail and edge cases because we have the dedicated space. I'll bring that up in the jam session today and if everyone's OK with it, set up a PR. How does that sound, Steyn?

**Comment by steynviljoen67** [comment]
Thanks Christoph, that makes sense to me. Thanks for picking it up for me.
🙏🏻
